### ISSUE TITLE
JBrowser issue

### ISSUE THREAD

**Issue by Denitz** [joomla/joomla-platform#1008]
Found notices in error.log of Joomla 2.5.3:
PHP Notice:  Undefined offset:  1 in /libraries/joomla/environment/browser.php on line 562

Current Joomla code for 562 is:

```
list ($this->_majorVersion, $this->_minorVersion) = explode('.', $version[1]);
```

**Comment by aaronschmitz** [comment]
This appears to be resolved in the latest version of the platform. The original code was:
preg_match('|Version[/ ]([0-9.]+)|', $this->_agent, $version);
list ($this->_majorVersion, $this->_minorVersion) = explode('.', $version[1]);

Code is now:
if (preg_match('|Version[/ ]([0-9.]+)|', $this->_agent, $version))
{
    list ($this->_majorVersion, $this->_minorVersion) = explode('.', $version[1]);
    return;
}

**Comment by griiettner** [comment]
I don't think this is solved.. I'm runing the lates version and still getting the notices on iPad and iPhones...

**Comment by youjoomla** [comment]
Can confirm this patch was never added since the 2.5.1 ,  browser.php line 562 is same in 2.51 and 2.5.6 . However the patch from aaronschmitz does work

**Comment by elinw** [comment]
@youjoomla  you could propose that as a patch on the 2.5.x tracker.

In the meantime as a platform issue this should be closed.
