### ISSUE TITLE
/html/select and /field/list

### ISSUE THREAD

**Issue by romacron** [joomla/joomla-platform#1014]
There is an big Mistake within the /form/field/list.php

in function getOptions

// Set some option attributes.
$tmp->class = (string) $option['class'];

// Set some JavaScript option attributes.
$tmp->onclick = (string) $option['onclick'];

and analog to display the JHtmlSelect:::options() and JHtmlSelect::option();

the format in getOptions and the format in JHtml are completely different.
Has someone of you get running an cssClass into an option.

Perhaps the Author of the Scripts can tell something about

**Comment by eddieajau** [comment]
I'm sorry, I don't understand the problem.  Please re-open the issue if you can provide more information.
