### ISSUE TITLE
JHttp: cannot use timeout and useragent

### ISSUE THREAD

**Issue by piotr-cz** [joomla/joomla-platform#1027]
**At this moment it's not possible to specify timeout or useragent string for transports.**

Although these exist in `JHttpTransport->request` interface and all derived transports, are not used in `JHttp` request methods (options, head, get, post, put, trace).

Right now, all transports are using timeout that is set in php settigs (default_socket_timeout, ~60s) which is way too long for some cases as REST or pinging (It's not possible to call the transport request method directly, as $transport is protected in JHttp).

The easiest way out would be to simply extend JHttp request methods to include $timeout and $useragent just as now $headers are.

However, JHttp instance holds $options (which is not used anywhere) and I guess this was intended to be used as a fallback when no $timeout is specified when using methods.

**My suggestion**

**1)  When instantiating JHttp, one can pass timeout and useragent as an option. This is passed to JHttpTransport right now.**

To JHttpTransports we add simple line to pick up those settings, so for JHttpTransportSocket this change from

```
if (!is_numeric($timeout))
{
    $timeout = ini_get("default_socket_timeout");
}
```

to

```
if (!is_numeric($timeout))
{
    $timeout = $this->options->get('timeout', ini_get("default_socket_timeout"));
}
```

*\* 2)  JHttp request methods are extended to pass $timeout and $useragent variables: **
from

```
public function post($url, $data, array $headers = null)
{
    return $this->transport->request('POST', new JUri($url), $data, $headers);
}
```

to

```
public function post($url, $data, array $headers = null, $timeout = null, $userAgent = null)
{
    return $this->transport->request('POST', new JUri($url), $data, $headers, $timeout, $userAgent);
}
```

I've created a topic on Platform group month ago describing exactly this thing:
https://groups.google.com/group/joomla-dev-platform/browse_thread/thread/38182a4a1b54cb9/1d7432371d5cca84

**Comment by realityking** [comment]
We wanna do 1), just no one has gotten around to writing it.

**Comment by piotr-cz** [comment]
Thanks for answering.

I can submit a patch, however I think it makes sense to allow setting timeout and useragent for each request (with fallback to Instance options). Points 1) and 2) in my Issue description are actually two things I'd like to see in the patch (not one or another).

**Scenario:**
I decide to ping an uri (using HEAD) to see if webservice is available or uri is correct before I send out the requests. 

```
$JHttp      = JHttpFactory::getHttp(JRegistry(array('timeout' => 30)));
```

For ping, I decide that there is sufficient timeout 5s:

```
$isAlive = $JHttp->head('http://google.com', null, null, 5);
```

For other more heavy requests I leave out the option as I already set when creating instance.

```
$response1 = $JHttp->post('http://google.com/API', $data1);
$response2 = $JHttp->post('http://google.com/API', $data2);
```

**Comment by realityking** [comment]
For timeout I tend to agree, for userAgent - why? IMO we should drop that argument completely.

**Comment by piotr-cz** [comment]
Supposedly some services require user agent string in request.

Most likely its meaningless to have an option to set it for every particular request like timeout, but I think it should be possible to set it at least in transport instance options.

**Comment by realityking** [comment]
That's what I mean, sorry if I was unclear. The userAgent should be settable trough the options, just not necessarily as an argument.

**Comment by piotr-cz** [comment]
I'll wait till monday in case somebody would have something to add and then add a pull request.

**Comment by aaronschmitz** [comment]
piotr-cz, do you want me to put together a pull request for this one?

**Comment by piotr-cz** [comment]
@aaronschmitz 
I've made a patch on local machine but didn't have to submit a pull request (It's a tax return time in my country).
I'll do it today and appreciate if you take a look at it.

**Comment by piotr-cz** [comment]
I've just added pull request (https://github.com/joomla/joomla-platform/pull/1101). Sorry for delay.
