### ISSUE TITLE
DDL for Tests

### ISSUE THREAD

**Issue by AmyStephen** [joomla/joomla-platform#1035]
Cannot be used to create a database.

https://github.com/joomla/joomla-platform/blame/staging/tests/schema/ddl.sql

AUTOINCREMENT should be AUTO_INCREMENT

TEXT fields are used for what should be char fields (and index builds fail.)

Is this DDL intended to be used with testing and MySQL?

**Comment by AmyStephen** [comment]
Also, I can't seem to find a config.php-dist file (or a config.php file) in the distribution.

I am trying to follow this documentation:

https://github.com/joomla/joomla-platform/blob/staging/docs/manual/en-US/appendices/analysis.xml#L38

But, it really doesn't seem to be related to the platform repository.

**Comment by mbabker** [comment]
That DDL is for SQLite, which should require no manual intervention (the database is built at runtime and deleted when finished, all in memory basically).  At https://github.com/joomla/joomla-platform/tree/staging/tests/suites/database/stubs resides driver specific DDL files.

**Comment by AmyStephen** [comment]
Thanks, Michael. I guess my bigger question is where are the instructions I should follow to set up unit testing? 

I started by looking at the Wiki - http://docs.joomla.org/Unit_Testing But that's outdated.

So, I remembered the discussion with Andrew and Chris on documentation and looked at the book, but that apparently isn't current, either. https://github.com/joomla/joomla-platform/blob/staging/docs/manual/en-US/appendices/analysis.xml

Do you have pointers on where newbies should get started with getting Joomla unit tests set up?

Thanks so much.

**Comment by robschley** [comment]
That is for Sqlite. The tests now run against a Sqlite in memory database
to make them easier to setup and faster to run.

Best,
Rob

On Sat, Mar 24, 2012 at 1:27 PM, Amy Stephen <
reply@reply.github.com

**Comment by mbabker** [comment]
The docs haven't been updated since things were updated to break away from needing specific configs and whatnot for each system.

At the most, I think all you'd need to do now to get running is just checkout the code and run phpunit.  That'll get you the basics.  To run the specific database tests, copy the phpunit.xml.dist file in the repo root to phpunit.xml and uncomment the `<php>` block then set up the values to your specific environment.

**Comment by AmyStephen** [comment]
Thanks guys - that helped a lot. Went ahead and did a PR to update the doc with your instructions.

https://github.com/joomla/joomla-platform/pull/1037

**Comment by eddieajau** [comment]
It's in SQLite format.  Don't try and run that in MySQL - it won't
work.  The DB specific DDL's are in /tests/suites/database/stubs/

Hope that helps.

Regards,
Andrew Eddie
http://www.theartofjoomla.com - the art of becoming a Joomla developer

On 25 March 2012 06:27, Amy Stephen
reply@reply.github.com
wrote:
