### ISSUE TITLE
Fatal error when caching view.json.php or other non-html

### ISSUE THREAD

**Issue by elpescador** [joomla/joomla-platform#110]
Also on Joomlacode.org: Joomla! CMS Issue Tracker > [#26455] Fatal error when caching view.json.php or other non-html

Caching goes well with html, but not with view.json.php ... Cache throws error
then when trying to call JDocumentJSON::getHeadData();

On Joomlacode.org I included a patch in which the controller of the component only activates workarounds when using 'html' as viewType. Maybe someone's got a nicer solution?

http://joomlacode.org/gf/download/trackeritem/26455/66681/controller.diff

**Comment by aaronschmitz** [comment]
This appears to have been fixed per (http://forge.joomla.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=26455).
