### ISSUE TITLE
grid.php calls isCheckedOut statically

### ISSUE THREAD

**Issue by blueboar2** [joomla/joomla-platform#1116]
I use Joomla 2.5.1, and my request is about file libraries/joomla/database/table.php. Now (in latest trunk joomla-platform - it is in libraries/joomla/table/table.php). But neverthless, request is the same. There is a function isCheckedOut in this file. I worked on my site and receive many such messages

"Strict Standards: Non-static method JTable::isCheckedOut() should not be called statically in /srv/www/libraries/joomla/html/html/grid.php on line 198"

isCheckedOut is not static, but there WAS a message in comments before function declaration: "@todo    This either needs to be static or not.". Now, after discussion in CMS bugtracker (http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=28326) it was removed.

There is such code in grid.php

if ($row instanceof JTable)
{
$result = $row->isCheckedOut($userid);
}
else
{
$result = JTable::isCheckedOut($userid, $row->checked_out);
}

If $row is not instance of JTable, isCheckedOut is called statically, and such "error" about Strict Standard occurs. What need i do to remove it?

**Comment by elinw** [comment]
You can use the web interface to edit the file and send a pull request.

**Comment by AmyStephen** [comment]
@blueboar2 - 

I'd probably just make it false (if $row isn't an instance of JTable, then it's not checked out).

if ($row instanceof JTable)
{
$result = $row->isCheckedOut($userid);
}
else
{
$result = false;
}

**Comment by blueboar2** [comment]
OK. I agree. Do it.

**Comment by blueboar2** [comment]
I've send pull request https://github.com/joomla/joomla-platform/pull/1143
