### ISSUE TITLE
General performance enhancements

### ISSUE THREAD

**Issue by okonomiyaki3000** [joomla/joomla-platform#1121]
I've noticed many places throughout Joomla! where slightly better choices could be made for the sake of performance. The main examples I've noticed are:

1) 'for' loops used when 'foreach' would be faster (and often require fewer lines of code)
2) if (count($someArray)) when if (!empty($someArray)) would be faster
3) long strings built by repeated concatenation when pushing to an array and imploding it would probably be better

I'm wondering, if I 'fix' these issues as I find them, will the changes be accepted or is there some reason that I'm not aware of for them being as they are? I realize these are small things and even if every instance of them is fixed throughout the entire framework, the gains would be negligible but they seem to be begging me to fix them.

**Comment by elinw** [comment]
I would seriously just fix and send pull requests as you find things. If you do it a bit at a time and then someone says no this  is why we did that, it's not a huge loss.

**Comment by LouisLandry** [comment]
Yes, please just send pull requests for improvements like that.  In some cases for loops are better than foreach (sometimes you just need an incremented value as you go over an associative array) but I'd be happy to look at, and merge, pull requests fixing these things up.
