### ISSUE TITLE
mobile detection is wrong (maybe)

### ISSUE THREAD

**Issue by romacron** [joomla/joomla-platform#1122]
libraries/joomla/application/web/client.php

Testet Plattform was an IPad and also an IPhone
both returns  Mac(7)

function detectPlatform ......

```
// Interestingly 'iPhone' is present in all iOS devices so far including iPad and iPods.
```

.....   elseif (stripos($userAgent, 'iPhone') !== false)
        {
            $this->mobile = true;
            $this->platform = self::IPHONE;

```
        // Let's look at the specific mobile options in the iOS space.
        if (stripos($userAgent, 'iPad') !== false)
        {
            $this->platform = self::IPAD;
        }
        elseif (stripos($userAgent, 'iPod') !== false)
        {
            $this->platform = self::IPOD;
        }
    }
```

We have tested an Ipad with this class/function an it returns MAC(7)
because in the $userAgent does not exists the string 'iPhone'
can someone check against ?

maby the function should be changed

**Comment by Buddhima** [comment]
Hi romacron,

Yes there seems to be a problem.
iPad user agent string doesn't contain word "iPhone"
Ref: http://www.labnol.org/tech/ipad-user-agent-string/13230/

In addition to that iPod also faces the same problem (iPod touch)
Ref: http://reviews.cnet.com/8301-19512_7-10115146-233.html

According to details obtained, I'll send a solution soon.

**Comment by romacron** [comment]
thanx, it should solve it.
Greetings Roman
