### ISSUE TITLE
JHttpTransportSocket timeout

### ISSUE THREAD

**Issue by rredpoppy** [joomla/joomla-platform#1142]
JHttp calls from the request method do not set a timeout, thus leaving the timeout with the default value. In JHttpTransportSocket, this implicit timeout is null and it's used in the connect method. 

For some reason, somewhere in this file, I get a connect timeout error. Curl wrapper seems to work fine, though. The error is a fatal exception 'Connection timeout'

**Comment by rredpoppy** [comment]
Example code that throws the exception:

``` php
        jimport('joomla.http');
        $transport = null;
        $transportWrappers = array('JHttpTransportCurl', 'JHttpTransportStream', 
            'JHttpTransportSocket');
        $options = new JRegistry();
        while (!$transport && $transportWrappers)
            try{
                $wrapper = array_shift($transportWrappers);
                $transport = new $wrapper($options);                
            }
            catch (Exception $e){
                continue;
            }
        $http = new JHttp($options, $transport);
        $getData = array('something'=>'else');
        $url = 'http://www.exmple.com';
        $response = $http->get($url, $getData);
```

**Comment by elinw** [comment]
Are you using ssl? 
I think https://github.com/joomla/joomla-platform/blob/staging/libraries/joomla/http/transport/socket.php#L243 should be handling but there seems to be a php bug if it is ssl
https://bugs.php.net/bug.php?id=41631
Can you check default_socket_timeout  in your environment?

**Comment by elinw** [comment]
Any update on this?

**Comment by eddieajau** [comment]
I'm sorry but we aren't accepting issues for this repository any more. Please see http://developer.joomla.org/cms/report-an-issue.html for how to report and issue for the CMS Platform.
