### ISSUE TITLE
JLoggerEmail Class

### ISSUE THREAD

**Issue by AmyStephen** [joomla/joomla-platform#1166]
Is there any interest in adding this class to the JLog package?

https://gist.github.com/2440666

I added it for Molajo and have it working with phpMailer. I think it could come in handy for emergency priorities to email a system admin when a database connection or backup fails or if a new version is available, etc.

This way I have it coded, it should work as a simple mail alert with the CMS (with the configuration file and also CMS Mailing classes.)

Not sure how I would test it in the framework since I doubt you want emails shooting out of unit testing. If there is interest in it, I'll look into how phpMailer testing was done. I could use that as a model.

If this is not something you need, it's not a problem. I have it -- and I'll share things for your consideration without concern. It's less for me to maintain -- but I have it for my needs, so am okay either way.

**Comment by LouisLandry** [comment]
I dig it.  I can honestly say that I didn't think about having something like that, and I should have.  It would be perfect as a catch for those really high priority events that get logged.  I think it would be neat to explore using the message in the subject line as well, or a truncated version of it.

**Comment by AmyStephen** [comment]
Good. Need to think about the testing. The Mailer testing doesn't appear to be filled out yet. Maybe I should start there and then go back to this class and do the testing? 

I'm brand spanking new at PHP Unit testing, so, it'll be good to learn.

**Comment by AmyStephen** [comment]
closing this for https://github.com/AmyStephen/joomla-platform/commit/1a30064c0dbc4ed7998fd2d5b99c2509ff618ec6 (I do not believe I can use this issue for my PR).
