### ISSUE TITLE
checkbox field doesn't return any value when not checked

### ISSUE THREAD

**Issue by fgossart** [joomla/joomla-platform#1172]
POST will contains checked box only, but when you use it within Jform /libraries/joomla/form/fields/checkbox.php modify last line by adding another input hidden before the original input permit $_POST to return an empty  value when not checked or the value when checked.

```
return '<input type="hidden" name="'.$this->name.'"><input type="checkbox" name="' . $this->name . '" id="' . $this->id . '"' . ' value="'
        . htmlspecialchars((string) $this->element['value'], ENT_COMPAT, 'UTF-8') . '"' . $class . $checked . $disabled . $onclick . '/>';
```

**Comment by elinw** [comment]
That's actually the proper behavior according to W3C standards for forms.

http://www.w3.org/TR/html4/interact/forms.html#h-17.2.1

**Comment by LouisLandry** [comment]
Ya, this is expected behavior from a checkbox.
