### ISSUE TITLE
scriptfile not supported by language, library, template

### ISSUE THREAD

**Issue by HLeithner** [joomla/joomla-platform#1179]
A scriptfile is not supported by these 3 installer types.

Looking at the php files shows no handling of the scriptfile tag.

**Comment by elinw** [comment]
see #901 also.

**Comment by eddieajau** [comment]
I think this is fixed now. If not, re-open the issue.

**Comment by TorstenE** [comment]
Hey Eddieajau, Joomla 3.3.6 does not Support install script in templates

**Comment by mbabker** [comment]
It was added to 3.4.0.
