### ISSUE TITLE
JMail is ignoring name parameter on addRecipient

### ISSUE THREAD

**Issue by ramalama** [joomla/joomla-platform#1190]
File: libraries\joomla\mail\mail.php

call to AddAddress omits the name parameter, but is should be passed to AddAdress

**Comment by elinw** [comment]
Can you make a pull request for this please?

**Comment by ramalama** [comment]
I tried but did not manage to commit it to my fork, so if I understand the mechanics of git right i can't make a pull request.

I found even more functions that ignore the second parameter $name completely: addReplyTo, addBCC and addCC.

**Comment by ramalama** [comment]
Hope I did everything right. 

I did only fix the addRecipient method. 

Since the code for addRecipient, addReplyTo, addBCC and addCC was almost the same you should consider to consolidate the duplicate code into a helper method using reflection or call_user_func_array.

**Comment by elinw** [comment]
Looks good, now you can close this issue.
