### ISSUE TITLE
Joomla PHP CodeSniffer Standards

### ISSUE THREAD

**Issue by neilferreira** [joomla/joomla-platform#1191]
Hi,

I am starting a new project in Joomla shortly and wanted all of my custom components etc to be following the Joomla Coding Standards.

I installed the PHPCS Standards as seen on http://docs.joomla.org/Joomla_CodeSniffer - but it appears very little of the 2.5 codebase actually validates in phpcs, so I won't be able to use it on my project without being bombarded with errors of the rest of the codebase.

Are the sniffs in the repository only meant for the base classes? Or how are users currently using the sniffs?

Cheers

**Comment by mbabker** [comment]
Currently, the CMS doesn't follow the standards, but it's a work in progress.  You could use the Platform's build.xml file, specifically the phpcs target, to help you build either a command line prompt or your own Ant/Phing command to run the code sniffer on only the files you specify.

**Comment by eddieajau** [comment]
I'd suggest posing the question on the CMS list.  Ideally all sources (with the exception of layout files - they are currently problematic) distributed by Joomla should conform to the standard, but it'll take a few people to just dive into the CMS and do some bulk updates.
