### ISSUE TITLE
missing imports prevent command line installation of extensions

### ISSUE THREAD

**Issue by amh-mw** [joomla/joomla-platform#1206]
Originally described in http://forum.joomla.org/viewtopic.php?f=624&t=716847

Steps to reproduce:
1. Download the english language extension from http://joomlacode.org/gf/project/jtranslation1_6/frs/?action=FrsReleaseBrowse&frs_package_id=5651 and unzip to /tmp
2. Modify the paths in the following script per your environment and run it
3. The installation will fail due to classes failing to autoload

``` php
#!/usr/bin/php
<?php
define('_JEXEC', 1);
define('JPATH_BASE', '/var/www/joomla');
require_once 'configuration.php';
require_once 'includes/defines.php';
require_once 'libraries/import.php';
JInstaller::getInstance()->install('/tmp/site_en-US');
?>
```

**Comment by mbabker** [comment]
This should go to the CMS repo (https://github.com/joomla/joomla-cms).  With the current Platform version, these classes will be auto-loaded, making the jimport statements unnecessary.  CMS 2.5 is using Platform version 11.4, which would need these jimport statements.

**Comment by amh-mw** [comment]
Roger that. Opening https://github.com/joomla/joomla-cms/issues/207
