### ISSUE TITLE
Array to string conversion PHP 5.4 strict in cache.php

### ISSUE THREAD

**Issue by mvanduijker** [joomla/joomla-platform#1231]
Notice: Array to string conversion in libraries/joomla/cache/cache.php on line 585
PHP 5.4 strict mode

Function array_diff_assoc does a strict check and casts values to string (see http://php.net/manual/en/function.array-diff-assoc.php). But the header variable sometimes have an array as value
<code>
array (size=3)
  '/media/system/js/mootools-core.js' => 
    array (size=3)
      'mime' => string 'text/javascript' (length=15)
      'defer' => boolean false
      'async' => boolean false
  '/media/system/js/core.js' => 
    array (size=3)
      'mime' => string 'text/javascript' (length=15)
      'defer' => boolean false
      'async' => boolean false
  '/media/system/js/caption.js' => 
    array (size=3)
      'mime' => string 'text/javascript' (length=15)
      'defer' => boolean false
      'async' => boolean false
</code>

Which causes this notice in libraries/joomla/cache/cache.php on line 585.

A fix would be to create an array_diff_assoc_recursive function / method.

**Comment by elinw** [comment]
Is that something you could write some code for?

**Comment by mvanduijker** [comment]
I have seen a couple of more php 5.4 stric notices. I am going to try to make some time to fix them.

**Comment by elinw** [comment]
Hi, have you been able to do that? It's easy to send a pull request to fix one file by using the web interface here at Github. Don't feel you have to find all of them to fix--every fix is helpful.

**Comment by mvanduijker** [comment]
I know, vacation and kind a busy at work. Will try to do asap.

**Comment by realityking** [comment]
I think this one is already fixed. Please confirm.

**Comment by mvanduijker** [comment]
Looks like it is fixed! Thanks!

**Comment by nulledcc** [comment]
Here some function that can be used to fix that issue
http://nl3.php.net/manual/en/function.array-diff-assoc.php#73972
