### ISSUE TITLE
JUser is initialized when we try to store using JTableCategory

### ISSUE THREAD

**Issue by fastslack** [joomla/joomla-platform#1252]
Im trying to insert a new category using the platform and JTableCategory class like:

```
$category = JTable::getInstance('Category', 'JTable', array('dbo' => $this->db_new));
$category->bind($object);
```

and i get this error:

```
Fatal error: Class 'JRequest' not found in /joomla-platform/libraries/joomla/session/session.php on line 526
```

Looking a bit into the code i see that into the store() method, the JUser class is called and it try to initialize a new session.

This is needed if we try to use the JUser table from platform/cli ?

**Comment by fastslack** [comment]
Seems that this is fixed on master and staging branches. Im using the 12.1 tag, im wrong to using it?

**Comment by LouisLandry** [comment]
You aren't wrong to use 12.1 ... it is just a bug in 12.1 that slipped through the cracks and was fixed more recently.  You should be safe using master I believe.

**Comment by fastslack** [comment]
Nope, im getting "Application Instantiation Error" because the store() method of the JTableCategory class is calling to JFactory to get the JUser instance, but im on CLI so no user/session is initialised.

libraries/joomla/table/category.php -> Line 202 

```
    public function store($updateNulls = false)
    {
        $date = JFactory::getDate();
        $user = JFactory::getUser();

        if ($this->id)
        {
            // Existing category
            $this->modified_time = $date->toSql();
            $this->modified_user_id = $user->get('id');
        }
        else
        {
            // New category
            $this->created_time = $date->toSql();
            $this->created_user_id = $user->get('id');
        }

        // Verify that the alias is unique
        $table = JTable::getInstance('Category', 'JTable', array('dbo' => $this->getDbo()));
        if ($table->load(array('alias' => $this->alias, 'parent_id' => $this->parent_id, 'extension' => $this->extension))
            && ($table->id != $this->id || $this->id == 0))
        {

            $this->setError(JText::_('JLIB_DATABASE_ERROR_CATEGORY_UNIQUE_ALIAS'));
            return false;
        }
        return parent::store($updateNulls);
    }
```

Im using the master branch now.

**Comment by elinw** [comment]
Is that the same issue as # 267?

Does your cli set a user for the created_by_user value?  If there is no session and value set from the application should it be null?

oops I meant #276

**Comment by fastslack** [comment]
yes is related with #276

I have not user set on my CLI script and i dont need it neither, so that causes the error. The "Application Instantiation Error" is from the JFactory::getUser()

**Comment by elinw** [comment]
@LouisLandry 

Louis would you mind taking a look at this whole set of issues and saying how much they all are part of the same underlying problem of JUser, JSession and JTable dependency?
#1356
#276
#1364
#1252
#227

I even thing #245 might actually be approachable if some of these dependencies were cleared up.

**Comment by elinw** [comment]
@fastslack  What if we only created the JUser if there was a session?

**Comment by fastslack** [comment]
@elinw I remember that i created a personal patch for this, that simply ignores the JFactory::getUser() if session not exists, but i cannot found it. That could be a solution.

**Comment by elinw** [comment]
I think you could perhaps check for a session_id. 
I think it would be useful in a number of places that I've been bumping into, most recently in writing some tests and having the JUser set up a null session before i can start running the tests for JSession.

**Comment by elinw** [comment]
@fastslack So I tried checking for session_id in two places in JUserHelper and it solved a number of the problems I' have been having with this.
