### ISSUE TITLE
Robot detection

### ISSUE THREAD

**Issue by stefanneculai** [joomla/joomla-platform#1254]
I have noticed that robot detection is missing in JApplicationWebClient, but it exists in JBrowser that is deprecated (https://github.com/joomla/joomla-platform/blob/staging/libraries/joomla/environment/browser.php#L626).

Should the robot detection be implemented in JApplicationWebClient or should it be in another class?

**Comment by elinw** [comment]
So a legitimate bot will always have a url in its UA string, so we could just detect http and know that covers them.  This also characterizes some feed readers and link checkers but that seems okay to me.

Some also have the strings 'spider' or 'bot' and it would be easy enough to check for them too.

**Comment by stefanneculai** [comment]
Fixed by pull request #1291
