### ISSUE TITLE
Tooltip

### ISSUE THREAD

**Issue by benjaminpick** [joomla/joomla-platform#1258]
How do we prevent user errors that occur because the special characters "::" are used otherwise? For example, title might end with an ":", or the title text might contain a "::" itself. In this case, the Javascript part splits up incorrectly and the tooltip text may be empty.

https://github.com/benjaminpick/joomla-platform/blob/0c096c5dfb93c5cec6bd4a38e8fcae13bc96bf9c/libraries/joomla/html/html.php#L757

Will add unit tests for this, but I don't know how to fix them - should we throw an error? Is there a way of escaping the : ? Should we add a space if the title ends by ':'?

**Comment by Buddhima** [comment]
Hi,
Throwing exception is one solution. Another solution may be use rarely use symbol (eg: ~ ) instead of colon pair(::). 
Is the colon pair is essential? 
Can you point out what are the places splitting by colon pair happens?

**Comment by benjaminpick** [comment]
JS Code:
https://github.com/joomla/joomla-platform/blob/master/libraries/joomla/html/html/behavior.php#L243

I'd be very careful with changing the special char, because it seriously
affects backwards compat (Maybe other functions creating tooltips were
written, or other plugin Javascript code relies on it, or even just that
the current assumption "~ is allowed, :: is not allowed" doesn't hold
anymore.)

Throwing an exception would only make blunt something that never worked
anyway. However, this is only useful for development, not if the text of
the tooltip was dynamic (e.g. as param of a plugin).

I was thinking if it was possible to introduce some kind of escaping the
: so that it doesn't conflict with :: anymore. (In the same way that \n
and \ works, maybe replace : by : and \ by \.)

**Comment by benjaminpick** [comment]
We could also, to reduce the issue to `'::'` only, concat the parts like
`$title . ' :: ' . $tooltip` and then trim them in the javascript.

**Comment by Buddhima** [comment]
Hi,
I also had similar idea like escaping the : . 
Then it is necessary to take care about : when get the original string.

If such thing can be applied, why don't we think about encoding the two parts before concatenate and decode after splitting,
In encoding : will be replaced by %3A

**Comment by piotr-cz** [comment]
I guess you should encode html characters, so colon becomes `&#58;`:

``` php
$tooltip = htmlspecialchars($user_input_value, ENT_COMPAT, 'UTF-8') . '::' . JText::_('JLIB_HTML_CHECKED_OUT');
```

But when you look at [com_content/helpers/icon.php/edit](https://github.com/joomla/joomla-cms/blob/master/components/com_content/helpers/icon.php#L100) It's done different way which should be buggy IMHO

**Comment by Buddhima** [comment]
Hi,
piotr-cz seems to have the same idea I had. 
So  benjaminpick, it seems to be encoding (including htmlspecialchars function) would done the job although it adds extra burden to the code.
If so I can fix it. But users should be aware that $tooltip doesn't contain the original text.

**Comment by piotr-cz** [comment]
While thinking about it, best place escape colons are indeed Views and  Template. If you find a place in the current codebase where it's not, please submit PR.

Encoded html characters should appear just like any onther text in the browser.

**Comment by benjaminpick** [comment]
htmlescaping everything might by to harsh, as tooltips currently can
contain HTML-Tags in the title. Why not just str_replacing : by its
html-entity?

Even if templates don't use this function, it is present in platform and
should be fixed or its flaws documented, I suppose.

**Comment by benjaminpick** [comment]
htmlescaping everything as in your template example solves a different
problem: $tooltip may contain a ", leading to invalid html.

The string is split in Javascript, so that the characters are already
un-escaped there. We'd need to double-encode the colon, arount the lines of:

``` php
$tooltip = str_replace($user_input_value, ':', '&#58;') . '::' .
JText::_('JLIB_HTML_CHECKED_OUT');
$tooltip = htmlspecialchars($tooltip, ENT_COMPAT, 'UTF-8');
```

**Comment by piotr-cz** [comment]
@benjaminpick :

I still think you should not unescape whole tootip, because Javascript won't be ale to separate tootlip title and body (see my example above). This is how it's done in mentioned JHtml::tooltip and this should work.

Please give an example of exact case of your issue with.

I've seen in the basecode that usually tooltip is generated directly, without mendioned class and might be that code contributor forgot to escape non - JText values.

**Comment by elinw** [comment]
Any new thoughts or code on this?

**Comment by dongilbert** [comment]
If this can be confirmed as a bug, and there's more interest in fixing this, please reopen with a pull request.

**Comment by piotr-cz** [comment]
As I wrote before, I believe this is not a bug.
Anyways, Twitter Bootstrap uses different format to for [tooltips](http://twitter.github.com/bootstrap/javascript.html#popovers) (there's only body) and [popovers](http://twitter.github.com/bootstrap/javascript.html#popovers) (title + data-content) so this becomes irrelevant.
