### ISSUE TITLE
JMail addRecipient, addCC, addBCC and addReplyTo problems

### ISSUE THREAD

**Issue by diananeculai** [joomla/joomla-platform#1266]
These methods were ignoring the $name parameter. This problem was solved for the addRecipient method, issue #1190, but it still has an untreated case: it uses array_combine(): <code>$combined = array_combine($recipient, $name);</code> and doesn't verify the returned value. If $recipient and $name accidentally don't have the same size then the returned value will be false and using it in <code>foreach ($combined as $recipientEmail=>$recipientName)</code> is not a good thing.

The same fix should be applied to addCC and addBCC. The addReplyTo method should be similar with these methods, but instead its parameters are different.

**Comment by elinw** [comment]
Would you submit the code to fix this?

**Comment by diananeculai** [comment]
Yes, I will, but after I finish what I have planed for this week for my project.

**Comment by chdemko** [comment]
Fixed
