### ISSUE TITLE
[bug] with JRegistry when the path contains empty fields

### ISSUE THREAD

**Issue by palcov** [joomla/joomla-platform#1279]
Hello. JRegistry throws fatal error:

http://forum.joomla.org/viewtopic.php?f=579&t=709422

It can happen if using large and not-so-thoroughly written components.
I not found this issue anywhere else. Thanks.

**Comment by elinw** [comment]
So what you can do is just edit the file and make the changes needed (try to follow joomla coding style). Then make a pull request based on that.

**Comment by elinw** [comment]
@palcov 
If you would browse to the appropriate file here in Github, click edit, and make the changes then save you will be able to send a pull request for this change.

**Comment by dongilbert** [comment]
This is fixed in the Framework.
