### ISSUE TITLE
JDatabaseQuery delete function not behaving correctly for join conditions

### ISSUE THREAD

**Issue by rredpoppy** [joomla/joomla-platform#1286]
The [delete method for the object](https://github.com/joomla/joomla-platform/blob/staging/libraries/joomla/database/query.php#L778) doesn't allow for delete statements using conditions on joined tables because it doesn't allow for extra columns after delete.

For instance, the correct delete statement is:

``` SQL
DELETE a.* FROM table1 AS a LEFT JOIN table2 AS b ON a.bid=b.id WHERE b.status=1
```

but the delete method does not allow to set columns after DELETE. If this is a specific MySQL implementation, it should at least be implemented in the driver class.

**Comment by elinw** [comment]
I'm not sure why this is marked issue fixed when there is no code.

**Comment by rredpoppy** [comment]
Me neither..

**Comment by eddieajau** [comment]
I'm sorry but we aren't accepting issues for this repository any more. Please see http://developer.joomla.org/cms/report-an-issue.html for how to report and issue for the CMS Platform.
