### ISSUE TITLE
JInput object in JSession

### ISSUE THREAD

**Issue by diananeculai** [joomla/joomla-platform#1309]
In JSession there is a variable defined as: <code>private $_input = null;</code>. In the rest of the code it is used <code>$this->input</code>.

I see 2 fixes for this issue: change the variable definition from $_input to $input or replace $this->input with $this->_input. Which would be better?

**Comment by realityking** [comment]
Good catch.

$this->_input is the correct solution since our code style says to use the underscore prefix for private variables.

**Comment by diananeculai** [comment]
Also, wouldn't it be a good idea to set the $_input variable in the _setOptions() method, like other private variables? Is this what the initialise() method should do? The method's comment is a bit confusing.
