### ISSUE TITLE
JImage::filter - The Grayscale image filter is not available.

### ISSUE THREAD

**Issue by artur-stepien** [joomla/joomla-platform#1384]
I'm building joomla cms gallery but there is problem with JImage filters. Filter class isn't loaded. 

Here is sample code:

``` php
$image = new JImage($src);
jimport('joomla.image.filters.grayscale');
$image->filter('grayscale');
```

When I run it, this error is thrown" "The Grayscale image filter is not available."

It works when I import class file manually using require_once.

**Comment by mbabker** [comment]
I see two issues here:

1) The filter classes aren't autoloadable due to the folder they are in being named filters.
2) The classname for the grayscale filter, JImageFilterGrayScale, isn't autoloadable due to the camelcase.

**Comment by artur-stepien** [comment]
I thought about the second one. 
Its pretty strange that JImage::getFilterInstance doesn't auto load filter class.

**Comment by mbabker** [comment]
They're both tied together.  The autoloader is looking for a file at libraries/joomla/image/filter/gray/scale.php with the class name as it is now.  The file is obviously not in that location.  Both issues are easily fixed.
