### ISSUE TITLE
Cell Merge in WYSIWYG Editor Issue

### ISSUE THREAD

**Issue by JoshKeegan** [joomla/joomla-platform#1410]
When merging two cells, Joomla's WYSIWYG editor inserts a rowspan="0". While this looks fine in most browsers which treat rowspan="0" as rowspan="1", Firefox (and possibly Opera) will span the rown to the bottom of the table, ruining table layout.

Reproduce the issue by:
1. Open the WYSIWYG Editor
2. Insert a table (with 2+ columns)
3. Highlight 2 cells on the same row
4. Right click & merge the cells
5. Insert some dummy test content
6. Open the page in Firefox

**Comment by realityking** [comment]
There's no WISWiG editor in the platform, you probably ended up in the wrong repository.

The Joomla CMS usesTinyMCE (https://github.com/tinymce/tinymce) as its default editor, if that's the editor you mean I recommend you report your issue there.
