### ISSUE TITLE
JUser load 

### ISSUE THREAD

**Issue by stefanneculai** [joomla/joomla-platform#1427]
When successfully loading a user, shouldn't guest set to false? Right now if you do <code>new JUser(id);</code> guest will be false and if you do <code>$user = new JUser; $user->load(id); </code> guest will be true.

**Comment by elinw** [comment]
Well it should be false unless the id is 0.  But yes, do you want to make a pull request to fix load()?
That should really be part of the test if you want to update that. That test should be doing  more detailed checking of expected properties.

**Comment by elinw** [comment]
@stefanneculai  Will you close this one please?

**Comment by stefanneculai** [comment]
I thought that would close by itself when the PR is merged.

Fixed by pull request #1474.

**Comment by realityking** [comment]
It does that only when the commit message is formatted in a certain way so you have to be careful if you want that behavior.
