### ISSUE TITLE
JFolder:folders fails when JPATH_ROOT is an empty string

### ISSUE THREAD

**Issue by aforgh** [joomla/joomla-platform#1442]
And, because of that, saving a menu item throws the following warning:
JFolder: :folder: Path is not a folder. Path: %s
(JLIB_FILESYSTEM_ERROR_PATH_IS_NOT_A_FOLDER_FOLDER)

The problem originates at line 116 of file libraries/joomla/database/table/menu.php:
        if ($this->parent_id == 1 && in_array($this->alias, JFolder::folders(JPATH_ROOT)))

The real question is: "is it correct for JPATH_ROOT to have an empty value? Shouldn't it default to '/', instead ?"

**Comment by realityking** [comment]
Since JPATH_ROOT should always be the absolute path to your application I wonder under what circumstances it became an empty string.

**Comment by aforgh** [comment]
It is indeed possible. See how JPATH_ROOT is set.
In index.php we have:
if (!defined('_JDEFINES')) {
    define('JPATH_BASE', dirname(__FILE__));
    require_once JPATH_BASE.'/includes/defines.php';
}
that sets the all important JPATH_BASE constant

Then in includes/defines.php - that gets loaded soon thereafter - we have:
$parts = explode(DIRECTORY_SEPARATOR, JPATH_BASE);
array_pop($parts);

//Defines.
define('JPATH_ROOT',            implode(DIRECTORY_SEPARATOR, $parts));

Given DIRECTORY_SEPARATOR = to /, whenever dirname(**FILE**) == '/', JPATH_ROOT becomes empty.

Unfortunately, more and more hosters are configuring their hosting solution to have the DocumentRoot of the virtual host chrooted to /, so having the website _apparently_ installed under the root directory of the webserver is not so uncommon.

**Comment by aforgh** [comment]
Try this code:

```
if (!defined('_JDEFINES')) {
    //$thisDir = dirname(__FILE__); // tThis is how Joomla sets JPATH_BASE
    // vv Force absolute path to //
    $thisDir = '/';
    define('JPATH_BASE', $thisDir);
    $parts = explode(DIRECTORY_SEPARATOR, JPATH_BASE);
    array_pop($parts);

    //Defines.
    define('JPATH_ROOT',            implode(DIRECTORY_SEPARATOR, $parts));
}

echo 'This dir :' . $thisDir . "\n";
echo 'JPATH_BASE :' . JPATH_BASE . "\n";
echo 'parts :' . print_r($parts) . "\n";
echo 'JPATH_ROOT :' . JPATH_ROOT . "\n";
```

**Comment by pasamio** [comment]
I'd argue that it shouldn't be set to an empty string to begin with and this is a bug in the bootstrap code that set it and it should be fixed there.
