### ISSUE TITLE
JString and JArrayHelper unit tests failing

### ISSUE THREAD

**Issue by aaronschmitz** [joomla/joomla-platform#1459]
On my installation, unit tests for JString and JArrayHelper that use unicode are failing.
https://gist.github.com/3377346

My configuration:
PHP 5.3.10-1ubuntu3.2 with Suhosin-Patch (cli) (built: Jun 13 2012 17:19:58) 
Copyright (c) 1997-2012 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2012 Zend Technologies
    with Xdebug v2.2.1, Copyright (c) 2002-2012, by Derick Rethans
    with Suhosin v0.9.33, Copyright (c) 2007-2012, by SektionEins GmbH

**Comment by elinw** [comment]
So given where the failures are I wonder if this relates to https://github.com/joomla/joomla-cms/issues/179

**Comment by aaronschmitz** [comment]
Ok. When I installed the fr_FR locale on my machine the problems in both JString and JArrayHelper went away. As far as I can tell, there's no way to make this function work properly without that locale, but I don't know much of anything about i10n so if anybody knows how to do this let me know. Otherwise, I'll submit a pull request to return incomplete if fr_FR is unavailable.

With regards to the CMS issue, I would say this is not related (or at least not directly related). I'm pretty confident, however, that I know the source of that bug so I'll post that over in the other thread.

**Comment by aaronschmitz** [comment]
Assuming some version of https://github.com/joomla/joomla-platform/pull/1464 is accepted, this issue is resolved.
