### ISSUE TITLE
JFormField strips all chars from the id attribute that are not 

### ISSUE THREAD

**Issue by ramalama** [joomla/joomla-platform#1469]
JFormField::getId($fieldId, $fieldName) does a <code>preg_replace('#\W#', '_', $id)</code> to replace "illeagal" characters.  In fact the replacement breakes the field.

However this is imho overrestrictive, probably not needed at all. I don't see a reason why the id attribute shall be treated differently from other attributes like name.

In my case it strips out german special characters like üäö etc. That's unwanted cause it prevents the Form to be loaded properly.

Suggestion: Either delete the <code>$id = preg_replace('#\W#', '_', $id);</code> line or replace it by a more accurate code. Plus add a comment why the replacement is necessary at all.

**Comment by elinw** [comment]
Could you submit code for that and possibly a test?

**Comment by ramalama** [comment]
Yes I probably could, first some questions to clarify what to implement:

Who knows why this replace is done?
Is there a good reason why this field is treated differently?

**Comment by LouisLandry** [comment]
A quick look at http://www.w3schools.com/tags/att_standard_id.asp shows that there are some restrictions on ID attribute valid characters.  Additionally, while in some versions of HTML/XHTML accented characters as well as period `.` and colon `:` are allowed, those characters have proven to be problematic for several browsers over the years as well as some JavaScript frameworks/libraries.  If we can assert that opening it up won't cause undue harm in those situations then I'd be happy for us to remove the restriction.

**Comment by ramalama** [comment]
Thanks @LouisLandry for the information! So this is not a issue but by design to follow the rules of html. 
Anyway the replacing was an unexpected behaviour for me: I would expect either an error thrown or just outputting the not html complainant element.

I'd suggest something like
<code><pre>if(!preg_match('#^[A-Za-z][A-Za-z0-9-_]_$#', $id))
    throw new Exception("The \$id:'$id' is invalid.  According to <a href='http://www.w3schools.com/tags/att_standard_id.asp'>w3schools.com</a> the \$id must match the RegEx ^[A-Za-z][A-Za-z0-9-_]_$ .");</pre></code>

Any thoughts on this?

**Comment by elinw** [comment]
I might put it in the docblock instead

**Comment by elinw** [comment]
@ramalama  Are you going to send a pull request for this?

**Comment by ramalama** [comment]
@elinw I'm really sorry, but I dont have any time to spend on this at the moment.

**Comment by dongilbert** [comment]
We do need to follow HTML restrictions, and it's easiest to just strip invalid characters. However, I can understand why you see it as a bug, since it was unexpected behavior. In my opinion, the CMS should have some sort of alert when filtering if the filtering results in data loss, as is the case here. Just to notify the user. However, this is implementation specific (meaning CMS) so I'm not sure it's something we need in the platform.
