### ISSUE TITLE
JTable::addIncludePath issues

### ISSUE THREAD

**Issue by imarklee** [joomla/joomla-platform#1489]
When a component has an exact user.php table file, it causes issue when you try to load up Joomla's user table object.

Example:

```
JTable::addIncludePath( '/path/to/com_custom/table/user.php' );

// Some custom codes
// from custom component goes here..
//

$user  = JFactory::getUser();
$table = $user->getTable();

// This will throw an error.
$table->load( '42' );
```

**Comment by elinw** [comment]
This is a longstanding discussion. You can find some advice about it here:
https://groups.google.com/d/topic/joomla-dev-platform/aOTn5eE1wr0/discussion

**Comment by LouisLandry** [comment]
This is a known issue.  We are moving away from the addIncludePath and towards leveraging the autoloader for these sorts of things now.  Thanks for the report.
