### ISSUE TITLE
JModelLegacy Incorrectly Determines Option

### ISSUE THREAD

**Issue by dongilbert** [joomla/joomla-platform#1499]
Line 216 of JModelLegacy will incorrectly parse your model class name if your model class ends in model. I had a situation where I was building an auto manager for a client, and one of the models was named AutosModelModel. The current regex parsed the classname and thought that the option was com_autosmodel, because it doesn't take into account the possibility that a model class can end in model.

**Comment by elinw** [comment]
Would you mind closing this one?

**Comment by dongilbert** [comment]
I opened the issue, then created the pull request, which also created an issue. :(  forgot about that part.
