### ISSUE TITLE
onContentPrepareForm event used for every prepareForm. (for exemple in MenusModelItem)

### ISSUE THREAD

**Issue by yanncharlou** [joomla/joomla-platform#1512]
I'm using the onContentPrepareForm event to dynamicaly load extras forms in MenuModelItem. 
But the event name used is the default one, called by the default preprocessForm function from JModelForm.

I've not found any clean way to ensure that the event 'onContentPrepareForm' is triggered by MenuModelItem or another model class.

It may be a good idea to change JForm class this way :
- add after line 30 :

```
    protected $event_prefix  = 'onContent'
```
- change line 228 this way :

```
    $results = $dispatcher->trigger($this->event_prefix.'PrepareForm', array($form, $data));
```

With this patch, event name will be changeable without overloading the whole preprocessForm method.

In MenusModelItem :
add after line 27 add :

```
protected $event_prefix = 'onMenuItem';
```

That's all.

**Comment by realityking** [comment]
onContentPrepareForm gets passed a JForm object. Each form has a name (JForm::getName()) to identify it so you can make sure you only modify the form you want to.

The disadvantage of your approach is that I may wanna modify two or three forms and I'd need one method for each form. With the current approach a simple in_array() check is sufficient.

**Comment by yanncharlou** [comment]
You are right. Your approach is better.

Thanks for your response.

Best regards,
Yann

Le 02/09/12 14:30, Rouven Weßling a écrit :

> onContentPrepareForm gets passed a JForm object. Each form has a name 
> (JForm::getName()) to identify it so you can make sure you only modify 
> the form you want to.
> 
> The disadvantage of your approach is that I may wanna modify two or 
> three forms and I'd need one method for each form. With the current 
> approach a simple in_array() check is sufficient.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/joomla/joomla-platform/issues/1512#issuecomment-8221456. 

## 

http://www.bulle-communication.com/ 
http://www.facebook.com/bullecommunication 
https://twitter.com/#%21/Bullecomm

**Comment by elinw** [comment]
@yanncharlou Would you mind closing this issue if it has been resolved?

**Comment by yanncharlou** [comment]
Ooops. So sorry. Of course. I close it.
