### ISSUE TITLE
Undefined method JHtmlSliders::getJSObject

### ISSUE THREAD

**Issue by eaxs** [joomla/joomla-platform#1526]
### Description

Calling the HTML sliders causes a fatal error in `libraries\joomla\html\sliders.php` on line 110 because the method is not defined in JHtmlSliders:

``` php
$options = self::getJSObject($opt);
```

Update: This happens the current beta1 release package.
#### To reproduce

Call the HTML sliders like this:

``` php
echo JHtml::_('sliders.start', 'slider-id', array('useCookie'=>1));
```

**Comment by realityking** [comment]
Thanks. This has already been fixed.
