### ISSUE TITLE
single quotes in JHtmlTabs::_loadBehavior lead to JS errors

### ISSUE THREAD

**Issue by harty83** [joomla/joomla-platform#1537]
In J3.0 beta1, there's this in html/tabs.php

$opt['titleSelector']               = "'dt.tabs'";
$opt['descriptionSelector'] = "'dd.tabs'";

$options = self::getJSObject($opt);

self::getJSObject has already been fixed to JHTML::getJSObject in a recent pull request.  But, by changing it to JHTML, the single quotes around dt.tabs and dd.tabs lead to double quotation leading to JS errors.  

Removing the single quotes seems to fix the issue:
$opt['titleSelector']               = "dt.tabs";
$opt['descriptionSelector'] = "dd.tabs";

Embarrassed to say that I'm not well versed in GIT yet and thus not sure how to do a pull request.  

Thanks,
Alan

**Comment by elinw** [comment]
Does #1555 take care of it? If so would you close this?

**Comment by LouisLandry** [comment]
This should be taken care of with #1555.  I'm going to close it in favor of that.  If it still is a problem after #1555 is merged please re-open it.  Thanks!
