### ISSUE TITLE
JFactory::getStream() and JVersion

### ISSUE THREAD

**Issue by johnathanhair** [joomla/joomla-platform#1540]
I believe I found an issie with JFactory::getStream() where it tries to use class JVersion. This is my first issue post. Please let me know how I can post issues better.

Version 12.1
File: factory.php
Line: 726

---- Current Code ---
726 $version = new JVersion;

728 // Set the UA for HTTP and overwrite for FTP
729 $context['http']['user_agent'] = $version->getUserAgent($ua, $uamask);

--- Proposed Code ---
726 // Set the UA for HTTP and overwrite for FTP
727 $context['http']['user_agent'] = someMethod($ua, $uamask);

function someMethod( $ua, $uamask )
{
// do something similar to
http://docs.joomla.org/API16:JVersion/getUserAgent
}

--- Other Notes ---

You can call new JStream() directly to get around but you have to define your own context

**Comment by realityking** [comment]
It's an issue alright.

That said, maybe we should define an interface for JVersion and allow injecting it. That way the platform can pick up the name and version number of the application where necessary.

**Comment by elinw** [comment]
@johnathanhair  Would you want to go ahead and send a pull request for this?
