### ISSUE TITLE
Showtables($name) is missing from the JDatabaseQuery?

### ISSUE THREAD

**Issue by compojoom** [joomla/joomla-platform#1542]
Hey guys,
Now I have no idea if that method has to be in JDatabaseQuery in the first place, but according to this here:
http://docs.joomla.org/JDatabaseQuery::showTables/11.1

there should be a showTables method. Now the thing is - I can't find it in 11.1 and in 12.1 and it is actually not in the current version here on github.

https://github.com/joomla/joomla-platform/blob/staging/libraries/joomla/database/query.php

So, was this method removed on purpose? I see that the postgre driver has it...

**Comment by pasamio** [comment]
I think the view was that it should be a JDatabaseDriver feature not a part of the query object. `getTableList` is the correct function name, I'm guessing the wiki used a different start point where that function did exist but wasn't final 11.1 version.

Ref: https://github.com/joomla/joomla-platform/blob/11.1/libraries/joomla/database/database.php#L650

**Comment by compojoom** [comment]
Ok, that is cool! However how do you do: 

   SHOW TABLES like '%something'

**Comment by eddieajau** [comment]
You would need to create that query manually, or suggest a change to
getTableList to account for it.

Regards,
Andrew Eddie
http://www.theartofjoomla.com - the art of becoming a Joomla developer

**Comment by elinw** [comment]
@compojoom  Do you want to close  this and then if you write a change as @eddieajau suggested do that as a pull request?

**Comment by dongilbert** [comment]
Since all the db drivers have their own way of getting the table names for the db, how about we add another method called `getFilteredTableList` to `JDatabaseDriver`. This could be implemented as a method that calls the `getTableList` method, and then filters based on the passed params. Something like:

```
/**
 * Method to get a filtered list of table
 * names that match passed regex param
 *
 * @param   string  $pattern    Regular expression to filter by
 *
 * @return  array   $tableList  List of table names that match $pattern
 */
final public method getFilteredTableList($pattern)
{
    $tableList = $this->getTableList();
    foreach ($tableList as $key => $table)
    {
        if (preg_match($pattern, $table) !== 1)
        {
            unset($tableList[$key]);
        }
    }

    return $tableList;
}
```

**Comment by ianmacl** [comment]
I'm not sure I see the use case.  Can you expand on what you're after?

**Comment by dongilbert** [comment]
Personally, I'm looking through open and unresolved issues on the platform and offering my take on it. I don't necessarily have an idea of a broad use case where this would come in handy. I just want to help reduce the # of open issues.

**Comment by elinw** [comment]
I guess if you had a naming structure for your tables you could find all of the tables that matched an element of that structure.

**Comment by dongilbert** [comment]
As this is relatively simple to get the table list matching the query, we don't need to add a new method, unless someone were interested enough to make it into a pull request and add a test.
