### ISSUE TITLE
undefined constant JPATH_SITE : in web application

### ISSUE THREAD

**Issue by bishnoi** [joomla/joomla-platform#1544]
Notice: Use of undefined constant JPATH_SITE - assumed 'JPATH_SITE' in .....\htdocs\jplateform\libraries\joomla\filesystem\path.php on line 15

emerges when testing for web application.

Don't know how put it up, but here is correction:

define('JPATH_ROOT', JPath::clean('JPATH_SITE'));

**Comment by elinw** [comment]
Would you turn that into a pull request?

**Comment by elinw** [comment]
@bishnoi  You can just browse to the file, click edit and make the proposed change. When you save it will give you the option to make a pull request.

**Comment by bishnoi** [comment]
ok Thanks

**Comment by IberoMedia** [comment]
Hello,

I am not sure how this system works, but I want to notify you that this notice is still coming up. I downloaded Joomla Platform 12.1 yesterday, from http://api.joomla.org/ and I am getting "Notice: Use of undefined constant JPATH_SITE - assumed 'JPATH_SITE' in ROOT\libraries\joomla\filesystem\path.php on line 12." After I added the quotes to the JPATH_SITE constant the warning dissappeared.

**Comment by dongilbert** [comment]
@IberoMedia - This is not an "issue" per se. When building with the Joomla Platform, you need to defined certain constants in your application bootstrap file. See this file here - https://github.com/JTracker/jissues/blob/master/includes/defines.php

and here - https://github.com/JTracker/jissues/blob/master/includes/boostrap.php

JTracker is an app built using the Joomla Platform. This a good example of how to bootstrap your applicaiton

**Comment by dongilbert** [comment]
IberoMedia, I responded to your comment on the issue,
https://github.com/joomla/joomla-platform/issues/1544
