### ISSUE TITLE
Method to generate a random token

### ISSUE THREAD

**Issue by stefanneculai** [joomla/joomla-platform#1575]
I think it would be nice to have in platform a method that generates a random token - similar to what <code>_createToken()</code> from JSession does. 

I would place it in JString, but I would like to know maintainers'  thoughts before.

Thanks!

**Comment by ianmacl** [comment]
I'm not really sure what it would do beyond what https://github.com/joomla/joomla-platform/blob/staging/libraries/joomla/crypt/crypt.php#L110 JCrypt::genRandomBytes does.  Was there anything specific you had in mind that wasn't covered by that method?

**Comment by stefanneculai** [comment]
I have searched in platform for such a method but never thought it can be in JCrypt. That's what I was looking for.
