### ISSUE TITLE
Legacy Tree Unit Test Coverage

### ISSUE THREAD

**Issue by dongilbert** [joomla/joomla-platform#1593]
I created a google doc here - https://docs.google.com/spreadsheet/ccc?key=0AqKlGgpGs6oOdDlYa21qN3R6ZllLNV83ZllnSUJZZ0E

The first column is the class that requires testing.
The second column is a select list of whether the test is completed. You can select yes, no or partial (if some of the tests are complete)
The third column is the name of the person that would like to be responsible for completing a test.

I'm busy going through all the current unit tests, marking their completeness level in the google doc. So when you go there, anything marked as red is an immediate need, the yellow is partially completed, and red is an immediate need.

**Comment by dongilbert** [comment]
Test closing this to see if I can reopen.

**Comment by dongilbert** [comment]
Yes, I now have the option to comment & reopen.

**Comment by eddieajau** [comment]
Ok, so you can re-open your own PR is you actually close it?

**Comment by dongilbert** [comment]
It looks like it. At least on issues it works that way.

**Comment by eddieajau** [comment]
Mmmm, probably not helpful to us but good to know.

**Comment by dongilbert** [comment]
Well, maybe we could make comments on a PR that needs some things, and request that the contributer close it until those things are addressed, at which point they can re-open.

However, I can totally see how it would create more problems, with people not willing or too lazy / proud to close their PR's.

**Comment by dongilbert** [comment]
I'm closing this because I discovered, (with the help of @elinw) this site: http://developer.joomla.org/coverage - this issue is now longer needed.
