### ISSUE TITLE
Unit Test Coverage Needed

### ISSUE THREAD

**Issue by elinw** [joomla/joomla-platform#1597]
The issue is that we are not at full unit test coverage in either the joomla or legacy branches but we need to be. Also even for coverage that we have there are improvements to be made.  
If you are working on a unit test project please put a comment below and then later you can link your pull request.

Resources:
[Joomla Test Coverage Report](http://developer.joomla.org/coverage/)
[Legacy Test Coverage Report](http://developer.joomla.org/coverage-legacy)

Documentation on Testing in Joomla
[Appendix A](http://developer.joomla.org/platform-manual.html)
(note: the version numbers on this document are innaccurate)

**Comment by dongilbert** [comment]
I am working on unit testing for the Legacy JModel\* set of classes. 

I've completed JModelLegacy which has already been merged - https://github.com/joomla/joomla-platform/pull/1588

**Comment by elinw** [comment]
I'm doing some work in JUserHelper.

**Comment by elinw** [comment]
#1694 includes full tests for the email rule.

The user helper tests were merged.

#1745  adds some more user test cases .

**Comment by eddieajau** [comment]
I'm sorry but we aren't accepting issues for this repository any more. Please see http://developer.joomla.org/cms/report-an-issue.html for how to report and issue for the CMS Platform.
