### ISSUE TITLE
Method loadResultArray used in Oracle driver but missed in base classes

### ISSUE THREAD

**Issue by SergeyLitvinov** [joomla/joomla-platform#1611]
In oracle.php we can see code:

```
    if ($includeDatabaseName)
    {
        $tables = $this->loadAssocList();
    }
    else
    {
        $tables = $this->loadResultArray();
    }
```

but loadResultArray method is missed in JDatabaseDriverOracle's parent classes JDatabaseDriverPdo and JDatabaseDriver.

**Comment by LouisLandry** [comment]
`JDatabase::loadResultArray()` was deprecated in favor of `JDatabaseDriver::loadColumn()`.  You should use that instead.

**Comment by mbabker** [comment]
As @SergeyLitvinov pointed out, the method is actually used in the driver [here](https://github.com/joomla/joomla-platform/blob/staging/libraries/joomla/database/driver/oracle.php#L365).

**Comment by ianmacl** [comment]
So the mentioned lines should be changed to use loadColumn.

**Comment by mbabker** [comment]
See #1613 :wink:
