### ISSUE TITLE
strict standards message after activating plugin "System - Cache"

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-platform#1617]
if the plugin (system-cach) is active in the frontend and backend we have following error:

Strict Standards: Declaration of JCacheControllerPage::store() should be
compatible with that of JCacheController::store() in
.../libraries/joomla/cache/controller/page.php on line 196

The messages only appear, if the plugin "System - Cache" is active.

Test Instructions:
activate the plugin "System - Cache" in the joomla backend then you see the errors

Database:
MySQL 5.2.x 
Status:
Referred to Platform Web Server:
Apache 2.2.x 
Platform Status:
No Platform Implications PHP:
PHP 5.3.x 
Build:
3.0.1-2-g294c62c
Browser:
Firefox 16

at the Version
Version: 3.0.1-8-gfa03fca

Backend: Strict Standards: Declaration of JCacheControllerPage::store() should
be compatible with that of JCacheController::store() in
/var/www/xxxx/html/privat/testi-3.0/j3/libraries/joomla/cache/controller/page.php
on line 196

Frontend:
Strict Standards:  Declaration of JCacheControllerPage::store() should be
compatible with that of JCacheController::store() in
/var/www/xxxx/html/privat/testi-3.0/j3/libraries/joomla/cache/controller/page.php
on line 196

Notice:  Undefined property: JSite::$registeredurlparams in
/var/www/xxxx/html/privat/testi-3.0/j3/libraries/joomla/cache/cache.php on line
658

Strict Standards:  Creating default object from empty value in
/var/www/xxxx/html/privat/testi-3.0/j3/libraries/joomla/cache/cache.php on line
661

joomlacode tracker item:
http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=29481

at the version Joomla! 3.0.2-269-g00ca8bd
the folloring error reportets:

Strict Standards: Declaration of JCacheControllerPage::store() should be compatible with that of JCacheController::store() in /html/joomla_testserver/libraries/joomla/cache/controller/page.php on line 196

you can test ist at "testserver.joomla-bugs.de/administrator/" (login are joomla-bugs/joomla-bugs)

**Comment by dongilbert** [comment]
The problem is that `JCacheController::store($data, $id, $group = null)` takes three params, and `JCacheControllerPage::store($wrkarounds = true)` takes only one. These are not compatible with each other, since they take different arguments, and that violates strict coding standards.]

I'm not sure what can be done to correct it, aside from rewriting the structure of `JCacheControllerPage`.

**Comment by elinw** [comment]
I believe that JM sent a pull request to deal with the issue, so this issue can be closed.

#1710

**Comment by infograf768** [comment]
the PR is here:
https://github.com/joomla/joomla-platform/pull/1710

**Comment by ImpulseWebdesign** [comment]
Is there also code that updates the cache plugin to add the extra arguments?

**Comment by dongilbert** [comment]
It's not the cache plugin that gives the error, it's the `libraries/joomla/cache` code that actually needs to change in order to fix the issue. It's not something we can do in this release, especially since we don't explicitly support 5.4 out of the box.
