### ISSUE TITLE
Warning: curl_setopt_array() [function.curl-setopt-array] and Strict Standards after clear the cach at joomla update

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-platform#1618]
hello,

if i clear the cach at Joomla Update I bekame the folloing errors:

Warning: curl_setopt_array() [function.curl-setopt-array]: CURLOPT_FOLLOWLOCATION cannot be activated when safe_mode is enabled or an open_basedir is set in /html/joomla_testserver/libraries/joomla/http/transport/curl.php on line 143

Strict Standards: Creating default object from empty value in /html/joomla_testserver/libraries/joomla/updater/adapters/collection.php(100) : eval()'d code on line 1

Strict Standards: Creating default object from empty value in /html/joomla_testserver/libraries/joomla/updater/adapters/collection.php(100) : eval()'d code on line 1

Database: MySQL 5.2.x
Web Server: Apache 2.2.x
PHP: PHP 5.3.x
Build: Joomla!3.0.2-269-g00ca8bd
Browser: Firefox 16 / IE8

gruß
zero-24

**Comment by elinw** [comment]
Would you send a pull request to fix this?

**Comment by eddieajau** [comment]
I'm sorry but we aren't accepting issues for this repository any more. Please see http://developer.joomla.org/cms/report-an-issue.html for how to report and issue for the CMS Platform.
