### ISSUE TITLE
sqlsrv startTransaction

### ISSUE THREAD

**Issue by MDunkleSr** [joomla/joomla-platform#1649]
/libraries/joomla/database/database/sqlsrv.php line 891 has incorrect syntax for MS SQL transaction.  

JDatabaseSQLSrv->transactionStart current:
        $this->setQuery('START TRANSACTION');

should be: 
        $this->setQuery('BEGIN TRANSACTION');

**Comment by elinw** [comment]
@MDunkleSr  You can just browse to the file, edit it and send the change as a pull request. Include #1649 in the comment so there is a link back to this.

**Comment by elinw** [comment]
Would you close this issue now? THhanks!
