### ISSUE TITLE
Minor Change to XPath

### ISSUE THREAD

**Issue by okonomiyaki3000** [joomla/joomla-platform#1668]
There's a change I'd like to make to `JForm::findFieldsByFieldset` but I want to get some opinions about it first. 

Currently there is a line (1495) that looks like this:

``` php
$fields = $this->xml->xpath('//fieldset[@name="' . $name . '"]//field | //field[@fieldset="' . $name . '"]');
```

I would like to change it to this:

``` php
$fields = $this->xml->xpath('//fieldset[@name="' . $name . '"]/field | //field[@fieldset="' . $name . '"]');
```

So the current situation is that the function finds all `field` elements which are descendants (any depth) of the `fieldset`. I'd like to change it so that only direct children are returned.

I don't think this will affect anything but you may ask why would I want to make such a change in the first place? I've been playing around with a new field type which I'm calling 'tuple' unless I can come up with a better name. It's a 'field' which has no value of its own but encloses a set of other fields. Anyway, I don't want to get into a complex explanation of it here but I'll just say that it works nicely and is quite useful but it currently causes problems when `JForm::findFieldsByFieldset` is used because that function will return the `tuple` field as well as each of its subfields.

**Comment by elinw** [comment]
I would think you'd want to make that optional, not change it. The ability to find them all seems very useful to me.

**Comment by okonomiyaki3000** [comment]
On the surface it would seem so but in practice I don't know if this is true. This is a protected function which is only called in one place. When someone calls `JForm::getFieldset` and passes the name of a fieldset (usually because they are building the input fields for some kind of parameters or something), this function will be called to get all the elements under that fieldset. I don't know of any reason that currently exists that `field` nodes would be nested any deeper. I believe they will always be direct children of `fieldset` nodes rather than some deeper level descendants.

**Comment by okonomiyaki3000** [comment]
Another way to rewrite it which would work just as well for my purposes would be:

``` php
$fields = $this->xml->xpath('//fieldset[@name="' . $name . '"]//field[not(ancestor::field)] | //field[@fieldset="' . $name . '"]');
```

This would still get all descendant `fields` from inside the `fieldset` just as the current situation with the exception that `fields` inside of `fields` would be ignored. There is not likely to be any case where you would want to get those nodes with this function. Why would you ever enclose `field` nodes within other `field` nodes except in a case such as the `tuple` type?

**Comment by LouisLandry** [comment]
The latter one I'm fine with.  The reason I am not a fan of your first attempt is because it is valid to have `<fieldset><fields><field /><field /></fields><field /></fieldset>` and I believe it would have unwanted behavior.

**Comment by elinw** [comment]
I just want to say that we do some complex nesting in some places  in the cms  and I wouldn't bet against any possible structure being used at least once. Still, I do agree that most of the time that would be for some kind of grouping and that in a lot of places (like the images field in content) where being able to group would be nice.

**Comment by okonomiyaki3000** [comment]
OK, thanks! I'll put together a pull request.
