### ISSUE TITLE
Post max_file_size limit

### ISSUE THREAD

**Issue by aschaefferfr** [joomla/joomla-platform#1699]
Hello,

I noticed that Joomla doesn't handle the error when a user try to upload a large file through the media manager.

I don't want tochange the setting of PHP in order to allow larger file to be uploaded. My wish is that Joomla warns the user that the file is too large.

the max_file_size limit of Apache

It's the first time, I report a bug. If I'm not used to the process of it. If I did something wrong, please don't hit me ;) (and tell me how to improve my bug report).

Here's my Joomla version:
Joomla! Version  Joomla! 2.5.7 Stable [ Ember ] 13-September-2012 14:00 GMT
Joomla! Platform Version     Joomla Platform 11.4.0 Stable [ Brian Kernighan ] 03-Jan-2012 00:00 GMT

Thanks in advance.
Arnaud

**Comment by elinw** [comment]
@aschaefferfr I promise, no hitting! Do you have some proposed code to change? Or do you need someone else to figure out that code?

**Comment by aschaefferfr** [comment]
Thank you for your answer.

I tried to give it a shot, but I'm not a master in PHP and I didn't find where the upload is handled.... I will continue to have a look a little bit. If I don't find anything, if someone else could have a look, it would be nice.

**Comment by LouisLandry** [comment]
Hi @aschaefferfr, I think your suggestion is sound, but if I'm not mistaken this is really just a messaging problem in the UI which could/should be handled by the CMS.  Have you discussed it with the JBS or posted the issue in the CMS tracker by chance?  http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemBrowse&tracker_id=8103

I'm going to close this and redirect you to the CMS crew for fixing the problem, but if something comes up where the platform is making this problem difficult to solve we'll revisit it then.  Thanks a bunch!
