### ISSUE TITLE
Error in Joomla.checkAll method's params documentation

### ISSUE THREAD

**Issue by CodeMaxter** [joomla/joomla-platform#1750]
The documentation of the Joomla.checkAll method's param is wrong, it shows documentation of the old version of this method.

The first param is not the number of checkboxes to check, is the checkbox with the assigned event.

Actual: @param mixed The number of box to 'check', for a checkbox element
Suggested: @param DomElement The checkbox with the assigned event.

**Comment by dongilbert** [comment]
If you're able, please edit that documentation for this item within github and make your changes. After that, you will be able to send in a pull request for that, and we can have the proper attribution back to you for this fix.
