### ISSUE TITLE
SQL installation script is not working in files installation packages

### ISSUE THREAD

**Issue by Serhioromano** [joomla/joomla-platform#1768]
[Issue tracker reference](http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_id=8103&tracker_item_id=29846)

Although it used to work with Joomla 2.5. Here is my discovery.

Before in manifest I used this and it worked.

``` xml
<install>
    <sql>
        <file driver="mysql" charset="utf8">components/com_cobalt/fields/multilevelselect/sql/install.field.multilevelselect.sql</file> 
    </sql>
</install>
```

It did not work in Joomla 3.0 and I found that file `libraries/joomla/installer/installer.php` on line 888 has this.

```
$sqlfile = $this->getPath('extension_root') . '/' . $file;
```

So `$sqlfile = $this->getPath('extension_root')` returns `/Users/joomla30/administrator/manifests/files/multilevelselect/` which is not exist. In fact even `/Users/joomla30/administrator/manifests/files/multilevelselect.xml` does not exists at this moment.

To get around I tried  to change `<file>` like this

``` xml
<install>
    <sql>
        <file driver="mysql" charset="utf8">../../../components/com_cobalt/fields/multilevelselect/sql/install.field.multilevelselect.sql</file>
    </sql>
</install>
```

so total of `$sqlfile = $this->getPath('extension_root') . '/' . $file;` would be

```
/Users/joomla30/administrator/manifests/files/multilevelselect/../../../components/com_cobalt/fields/multilevelselect/sql/install.field.multilevelselect.sql
```

but since `/Users/joomla30/administrator/manifests/files/multilevelselect/` is non-existent it returns error on Unix type systems.

I mean even if I try in terminal

```
cd /Users/joomla30/administrator/manifests/files/multilevelselect/../../../components/com_cobalt/fields/multilevelselect/sql/
```

It will return that directory does not exists.

I get this error on install

![Screen Shot 2012-12-21 at 9 39 10 PM](https://f.cloud.github.com/assets/650741/27126/e226be54-4b73-11e2-8746-cfbcce78ba4d.png)

And this when try to uninstall

![Screen Shot 2012-12-21 at 9 38 36 PM](https://f.cloud.github.com/assets/650741/27127/e55157ce-4b73-11e2-9780-3df2762ad7a7.png)

And this problem only with file type installation

```
<extension version="3.0" type="file" method="upgrade">
```

**Comment by mbabker** [comment]
The installer package has moved to the CMS, please report this issue there.
