### ISSUE TITLE
Impossible to update extensions via "extension" update and 0 client id

### ISSUE THREAD

**Issue by Denitz** [joomla/joomla-platform#1776]
JUpdaterExtension always sets client_id of extension to 1:
$this->current_update->client_id = 1;

This makes impossible of updating extensions which have 0 client_id.
I.e. I have a package with this update servers declaration:
<updateservers>
    <server type="extension" priority="1" name="AlterBrains Updates">http://www.site.com/update.xml</server>
</updateservers>

no matter what <update>..</update> section of my XML has - JUpdaterExtension always search for extension with client_id=1, so my package fails because packages have 0 client_id.

**Comment by eddieajau** [comment]
I'm sorry but we aren't accepting issues for this repository any more. Please see http://developer.joomla.org/cms/report-an-issue.html for how to report and issue for the CMS Platform.
