### ISSUE TITLE
Add documentation to the Platform Manual explaining how to edit a file using Gituhub

### ISSUE THREAD

**Issue by eddieajau** [joomla/joomla-platform#1784]
It would be helpful to have a reference document in the Platform wiki https://github.com/joomla/joomla-platform/wiki to walk people through how to make simple changes to single file where those people are not comfortable with command line or application driven git. Examples with screenshots should include how to edit an existing file and how to add a new file.

**Comment by elinw** [comment]
@eddieajau  If you want to just copy the page from the docs wiki that would be fine.
http://docs.joomla.org/Github_using_the_web
