### ISSUE TITLE
Making JLog compliant with PSR3

### ISSUE THREAD

**Issue by florianv** [joomla/joomla-platform#1799]
PSR3 logger is nice, we could import these interfaces in Joomla and "rewrite" the logger so it is PSR3 compliant.

https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-3-logger-interface.md

If people want to use more sophisticated handlers they could aways use some of :
https://github.com/Seldaek/monolog/tree/master/src/Monolog/Handler

It also comes with the question of which names for interfaces to use.
The standard is to prefix abstract classes with `Abstract` and suffix interfaces with `Interface`.

If we could adopt this convention, then we can directly import the code from the PSR3 Standard.

**Comment by eddieajau** [comment]
> If people want to use more sophisticated handlers they could aways use
> some of :
> 
> https://github.com/Seldaek/monolog/tree/master/src/Monolog/Handler
> 
> But we already have that capability (for extension) in JLog. Why would you
> want to take that away?

**Comment by florianv** [comment]
Just looking, I thought they defined an interface for the log handlers but it looks like no in fact. Only Logger + Log and levels which are quite similar to what Joomla actually has.

Would have been nice to add LogHandlerInterface too

**Comment by eddieajau** [comment]
Yeah, but complying with an interface doesn't mean we have to rip out
perfectly good functionality. All you need to do is add the interface and
proxy the required methods back to our existing functions.

**Comment by florianv** [comment]
Yes, since we have the same error levels in Joomla it shouldn't be a big big task.

The constructor should become public https://github.com/joomla/joomla-platform/blob/staging/libraries/joomla/log/log.php#L123

In this case https://github.com/php-fig/log/blob/master/Psr/Log/LoggerInterface.php#L113 can be the same than `JLog::add` and we can add a non static method `setLogger`that do the same than `addLogger`

**Comment by florianv** [comment]
For the dependency on the Psr repo we should add it to our composer.json file instead of copying the whole code in the log package.

Since our code will be PSR0 compatible, we will be able to autoload the Psr package.

**Comment by eddieajau** [comment]
You wouldn't copy it into the Log package. You'd copy it into a FIG (or yet to be agreed) vendor /libraries/FIG or maybe it will be /libraries/PSR (which I think is preferred but it's bit like making RFC a vendor ... huh?). But for it not to be included, we'd have to talk about modifying the documentation to tell people how to build the Platform. I'm still not convinced we should put all our eggs in the one basket and rely only on Composer (in other words, include the PSR interface anyway).

**Comment by florianv** [comment]
Yes. We could add the composer.json file and have the library copied in vendor/Psr (like that it matches the folder in which composer will install it). So there is still this fallback for people using the full joomla platform without installing it via composer.

**Comment by realityking** [comment]
Just as an FYI, I wrote this a couple of days ago: https://github.com/realityking/joomla-platform/compare/psrlog#diff-11

It provides a simple class implementing the PSR-3 interface that internally uses Joomla's logging mechanism. It's not complete but it should serve as an example how it could be done.

**Comment by florianv** [comment]
@realityking looks nice. I think JLog could extend `AbstractLogger` and implement the `log` method in favor of the static `add` method that could be deprecated.

**Comment by dongilbert** [comment]
I think we can retain the folder structure we currently have in regards to "vendor". I have a PR open that adds a few lines to the composer.json file which tells composer where to install packages. I would elect to retain the libraries structure if we can b

**Comment by AmyStephen** [comment]
Awesome guys. OK, maybe we don't need three interfaces for the platform to the same package. 

@realityking  - looks like you have taken care of things. Would it make sense for us to test out your work and issue PR's (if needed) on your fork? 

Assuming that's acceptable, I'll update the discussion on list about moving forward with the JLog interface that Rouven has this covered and where those interested can participate.

**Comment by eddieajau** [comment]
Wasn't this where Jira was going to come in, or has that idea fallen by the
wayside already?

## 

Regards,
Andrew Eddie
http://learn.theartofjoomla.com - training videos for Joomla developers

**Comment by AmyStephen** [comment]
Actually, I think he's waiting on feedback. I know he's put a great of time into setting up the application. He walked me through it a week, or so, ago. Following that, I saw he had posted on list but I don't believe there was a response. I asked if he'd be your right-hand man on this and stay with it, he assured me that was the plan.

**Comment by florianv** [comment]
I did quickly an example about JLog

https://github.com/florianv/joomla-platform/blob/jlog/libraries/joomla/log/LogHandlerInterface.php
https://github.com/florianv/joomla-platform/blob/jlog/libraries/joomla/log/LogEntry.php
https://github.com/florianv/joomla-platform/blob/jlog/libraries/joomla/log/Log.php
https://github.com/florianv/joomla-platform/blob/jlog/libraries/joomla/log/logger/CallbackHandler.php

**Comment by eddieajau** [comment]
Well, the way I'm thinking is that the additions to our standards/policy
can happening a separate pull, combining Don's RFC. If we hone that it
makes it easier to present for wider community consultation, and it is
easier for the PLT to discuss and ratify. In the mean time, those
contributing to the code can be ironing out issues.

## 

Regards,
Andrew Eddie
http://learn.theartofjoomla.com - training videos for Joomla developers

**Comment by realityking** [comment]
Didn't read this until today.

@AmyStephen The code is quite complete, I'll have to add the context stuff before it's worth testing. I'll try to get to that this week.
