### ISSUE TITLE
JLoader::NotLoading

### ISSUE THREAD

**Issue by Xerosigma** [joomla/joomla-platform#1804]
Using the version of J! Platform that comes with the latest version of J! CMS, auto loading using registerPrefix or discover doesn't seem to work.

The below does squat, my files and class names follow convention:
JLoader::registerPrefix('Jehuti', JPATH_PLATFORM . '/../components/com_jehuti/controllers/');
JLoader::discover('Jehuti', JPATH_PLATFORM . '/../components/com_jehuti/controllers/');

However if I load individual files, works fine:
Loader::register('JehutiController', JPATH_PLATFORM . '/../components/com_jehuti/controllers/jehuti.php', true);
JLoader::register('JehutiModel', JPATH_PLATFORM . '/../components/com_jehuti/models/jehuti.php', true);
JLoader::register('JehutiView', JPATH_PLATFORM . '/../components/com_jehuti/views/jehuti.php', true);

**Comment by dongilbert** [comment]
You're approaching if with the right idea, but your implementation is slightly off. Where is are you running this code? In your com_jehuti/jehuti.php file? If so, your call should be registerPrefix('Jehuti', **DIR**);

Then, when using a class, it will look for JehutiModel in com_jehuti/model/model.php and JehutiModelBase in com_jehuti/model/base.php

However, you must note, that if your building this in the CMS as a component, you'll have issues withe the default configuration. I can send you a screenshot of my directory structure if you'd like later when I'm on my computer.

**Comment by Xerosigma** [comment]
Thanks, I would really appreciate a if you could send me a diagram or
screen shot of a working structure for CMS.
Currently this is mine:
[image: Inline image 1]

I'm running the code from the highlighted file: _com_jehuti/site/jehuti.php_
I'm assuming this is wrong?

On Thu, Jan 17, 2013 at 1:33 AM, Don Gilbert notifications@github.comwrote:

> You're approaching if with the right idea, but your implementation is
> slightly off. Where is are you running this code? In your
> com_jehuti/jehuti.php file? If so, your call should be
> registerPrefix('Jehuti', **DIR**);
> 
> Then, when using a class, it will look for JehutiModel in
> com_jehuti/model/model.php and JehutiModelBase in com_jehuti/model/base.php
> 
> However, you must note, that if your building this in the CMS as a
> component, you'll have issues withe the default configuration. I can send
> you a screenshot of my directory structure if you'd like later when I'm on
> my computer.
> 
> Sent from my iPhone
> 
> On Jan 17, 2013, at 1:20 AM, "Nestor E. Ledon" notifications@github.com
> wrote:
> 
> > Using the version of J! Platform that comes with the latest version of
> > J! CMS, auto loading using registerPrefix or discover don't seem to work.
> > 
> > The below does squat, my files and class names follow convention:
> > JLoader::registerPrefix('Jehuti', JPATH_PLATFORM .
> > '/../components/com_jehuti/controllers/');
> > JLoader::discover('Jehuti', JPATH_PLATFORM .
> > '/../components/com_jehuti/controllers/');
> > 
> > However if I load individual files, works fine:
> > Loader::register('JehutiController', JPATH_PLATFORM .
> > '/../components/com_jehuti/controllers/jehuti.php', true);
> > JLoader::register('JehutiModel', JPATH_PLATFORM .
> > '/../components/com_jehuti/models/jehuti.php', true);
> > JLoader::register('JehutiView', JPATH_PLATFORM .
> > '/../components/com_jehuti/views/jehuti.php', true);
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/joomla/joomla-platform/issues/1804#issuecomment-12357403.

## 

_Nestor Ledon_

CEO | Terra Chaos Corporation | www.terrachaos.com http://terrachaos.com

**Comment by dongilbert** [comment]
Here's a basic structure: http://d.pr/i/5qF7

And here's my components bootstrap file: http://d.pr/i/FX4

I'm going to write up a blog post about it eventually. Not sure when I'll
have time though. Hope it helps.

**Comment by Xerosigma** [comment]
Thanks a ton. If I'm not mistaken though,my deployed structure is the same as yours. I'll review your bootstrap maybe I'm missing something.

![app-struc](https://f.cloud.github.com/assets/2592281/75817/7739faec-60d7-11e2-90e1-db99585cb77c.png)

Thanks again for the response.

**Comment by dongilbert** [comment]
The main difference is, if you register a prefix, it follows a pattern when
trying to autoload the file.

So I have registerPrefix('RV', **DIR**). When I try to use RvModelResort,
it looks for it in **DIR** . '/model/resort.php';

Have a look at the JLoader documentation here:
http://joomla.github.com/joomla-platform/

**Comment by Xerosigma** [comment]
Oh dear... I have it working. My directories where not named correctly. I had "controllers" instead of "controller."

Thanks a ton for the help.
