### ISSUE TITLE
JTableAssets::rebuild() does not work

### ISSUE THREAD

**Issue by irezvin** [joomla/joomla-platform#1824]
JTableAssets does not have its own rebuild() implementation.

Implementation of JTableNested::rebuild() relies on presence of 'alias' and 'path' fields, which are absent in #__assets table.

**Comment by elinw** [comment]
THere isn't such a function. YOu only approach the assets table indirectly. It can self heal if you have messed it up, but as long as you don't try to do anything directly to the assets table it won't get messed up.  Unfortunately that is not the actual nature of human beings using open source software hence he reason for application like assetFix.  The right way to heal the assets table is by stimulating the api to run by doing a save in all the tables you have that track assets.
