### ISSUE TITLE
Error with Reply-To Name handling, names are lost 

### ISSUE THREAD

**Issue by GreyHead** [joomla/joomla-platform#1845]
In Joomla! 3.0.3 the mail.php handles Reply To names incorrectly, the result is
that the Names are not included with the Reply-To address.

In libraries/Joomla!/mail/mail.php around line 463 is

```
$this->addReplyTo(array($replyTo[$i], $replyToName[$i]));
```

This line uses an array to send the Email address and name to the function
around line 345

```
public function addReplyTo($replyto, $name = '')
```

which expects two separate parameters, not an array.

The fix is to remove the array from line 463:

```
$this->addReplyTo($replyTo[$i], $replyToName[$i]);
```

**Comment by GreyHead** [comment]
See a patch which fully addresses this issue
http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_id=8103&tracker_item_id=30246

**Comment by eddieajau** [comment]
I'm sorry but we aren't accepting issues for this repository any more. Please see http://developer.joomla.org/cms/report-an-issue.html for how to report and issue for the CMS Platform.
