### ISSUE TITLE
Can not overwrite existing field.

### ISSUE THREAD

**Issue by zsinryu** [joomla/joomla-platform#1857]
https://github.com/joomla/joomla-platform/blob/staging/libraries/joomla/form/form.php

At "load" function, $replace = true.

`public function load($data, $replace = true, $xpath = false)`

`$addeddom = $olddom->ownerDocument->importNode($loadeddom);`

We can not import child nodes &lt;option&gt; like

``` xml
<field name="fieldname" type="list" default="0" label="FIELD_LABEL" description="FIELD_DESC">
  <option value="1">1</option>
  <option value="2">2</option>
  <option value="3">3</option>
</field>
```

DOMNode DOMDocument::importNode ( DOMNode $importedNode [, bool $deep ] )

So, in the result, the new field does not contains any option.

Please fix this.

**Comment by elinw** [comment]
Is this an issue you are having in the CMS? Would you send this to the cms along with instructions on specifically how to reproduce the error? THanks

**Comment by eddieajau** [comment]
I'm sorry but we aren't accepting issues for this repository any more. Please see http://developer.joomla.org/cms/report-an-issue.html for how to report and issue for the CMS Platform.
