### ISSUE TITLE
version 3.1.4 - problem with jQuery

### ISSUE THREAD

**Issue by alexgru** [joomla/joomla-platform#1866]
Hello.

I have problem with new version Joomla CMS 3.1.4 , in this version by default including jQuery library and jQuery No Conflict and Bootstrap library - this very no good !
For example , in my template I use bootstrap library with jQuery , but now I have conflict with 2 including jQuery library .
I dont want everytime waiting when joomla cms update bootstrap library and jquery I use latest version and I don`t want including Joomla  "JHtml::_('bootstrap.framework');"
In version before 3.1.4 I can dont including this code "JHtml::_('bootstrap.framework');" and all work fine , but in this version I cant disable "JHtml::_('bootstrap.framework'); "

Sorry for my English .

**Comment by mbabker** [comment]
This issue is for the CMS, please report it to the CMS repository.
