### ISSUE TITLE
Please help to solve the problem with Joomla

### ISSUE THREAD

**Issue by makabs** [joomla/joomla-platform#1872]
Recently moved to another site hosting, then there were these mistakes. In joomle multiyazynost used, and this function does not work
This is a error code: Notice: Array to string conversion in /var/www/vhosts/weburl/httpdocs/libraries/joomla/cache/cache.php on line 585

Notice: Array to string conversion in /var/www/vhosts/weburl/httpdocs/libraries/joomla/cache/cache.php on line 585

**Comment by mbabker** [comment]
This repo is no longer in active development. Please see https://github.com/joomla/joomla-cms
