### ISSUE TITLE
Tiny issue on JDate week magic get property help text

### ISSUE THREAD

**Issue by GeoTimber** [joomla/joomla-platform#1873]
in 
joomla-platform/libraries/joomla/date/date.php
on line 29 it reads
- @property-read  string   $week          W - Numeric representation of the day of the week.

It think it should read
- @property-read  string   $week          W -ISO-8601 week number of year, weeks starting on Monday 

it confused me for a second or two.
thanks for everything! Joris

**Comment by mbabker** [comment]
> [READ-ONLY] This repo is no longer in active development. Please see https://github.com/joomla/joomla-cms
