### ISSUE TITLE
No valid using of the cache in JModelList 

### ISSUE THREAD

**Issue by Flamefire** [joomla/joomla-platform#223]
In JModellist the cache is queried with if (!empty($this->cache[$store])) {

But in some cases the value in the cache is zero and so mistakenly threated as
not set. So the function gets executed and (in case of getTotal()) will cause
redundant database queries. In my case I noticed it while watching the log and
wondering why a query is submitted 3 times!

So I suppose empty() should be replaced by unset()

See also: http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_id=8103&tracker_item_id=26116

**Comment by aaronschmitz** [comment]
This issue has been fixed - all queries are now if (isset($this->cache[$store])).
