### ISSUE TITLE
possible fatal error in JUser::load()

### ISSUE THREAD

**Issue by Hoffi1** [joomla/joomla-platform#227]
Because JTable::getInstance() could return false (e.g. if an extension unfortunately registers a user.php file for it's own table object) the line "if (!$table->load($id))" could cause a fatal error.

To solve it (at this point) change the line to "if (!$table or !$table->load($id))"

But, of course, best solution would be if JTable::getInstance() could handle different classes stored in files with same name (in different folders).

Thanks,
Hoffi

(also submitted on http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=26628)

**Comment by eddieajau** [comment]
Can you try something for me.  If you are having this problem in the backend, can you find /administrator/includes/framework.php and after the `jimport('joomla.user.user')` put:

```
JLoader::register('JTableUser', JPATH_PLATFORM.'/joomla/database/table/user.php');
```

Also do this in the frontend `/includes/framework.php` file.  I think that may solve the problem.

**Comment by Hoffi1** [comment]
Hi Andrew,

thanks for your suggestion. I have tried this and I think I must correct my report. The fatal error I had seen on an Joomla 1.6.4 with Discussions 1.3. There your suggestion doesn't help. Then I have tried this on a fresh Joomla 1.7.0 and I can't reproduce the error. I don't know how but 1.7 seems to be able to handle multiple files named user.php to load the correct JTable derived class.
I had renamed Discussions' files on our site to solve the problem completely before we upgraded to 1.7. Because I had not found any relevant differences in JTable, JPath, and JUser I was sure the problem is also present on 1.7 - which seems to be a wrong mind.
But one (design) question is left: Is it generally allowed / a good idea having files like user.php in a folder registered via JTable::addIncludePath() or should all these files have unique names to prevent conflicts? JPath returns only one path containing a file with matching name. And JTable::getInstance() returns false if this file doesn't contain the class requested regardless if another path contains the right file. So I see the potential for the fatal error I originally described although I can't see it any longer in "real world".

Many thanks and sorry for my wrong conclusion,
Hoffi

**Comment by chdemko** [comment]
See https://github.com/joomla/joomla-platform/pull/397

**Comment by elinw** [comment]
The issue Christophe referenced has been closed ... what does that mean for this issue?

**Comment by LouisLandry** [comment]
This has been fixed along the way.  Closing it.  If we have a regression feel free to re-open.
