### ISSUE TITLE
JCache doesn't work as expected caused by incomplete/wrong modifications (J 1.7.0 / Platform 11.1)

### ISSUE THREAD

**Issue by Hoffi1** [joomla/joomla-platform#228]
There are changes made on library/cache/cache.php which cause problems:

The function JCache::_getStorage() uses $this->_handler but $_handler is declared as static. Using self::$_handler instead of $this->_handler is good but not enough. Because $_handler is initialized with array() (Why?) the check isset(self::$_handler) is always true so $_handler never gets an JCacheStorage instance. So an empty array would be returned by _getStorage() which would cause a fatal error in caller on e.g. $handler->getAll() (because $handler is array()).

Please check if making $_handler static is correct and why it is initialized with array() (it is expected to hold an JCacheStorage object in normal use-case).

Thanks,
Hoffi

(also committed on http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=26627)

**Comment by Hoffi1** [comment]
This bug was fixed by klas on May 27 here (https://github.com/joomla/joomla-platform/blob/0cf636132a2d087eea97f19bc6dd86ac9d184a9d/libraries/joomla/cache/cache.php) but is not part of Joomla! 1.7.0.

Hopefully it will find it's way into Joomla! 1.7.1...

**Comment by elinw** [comment]
Please update your issue category on joomla code to platform synch and put a link to that commit.

**Comment by Hoffi1** [comment]
I had put a link to the commit on joomlacode but because it was closed by Andrew I'm not able to change anything.

**Comment by eddieajau** [comment]
Fixed in platform so closing issue.
