### ISSUE TITLE
Format an empty datetime string

### ISSUE THREAD

**Issue by tampe125** [joomla/joomla-platform#233]
if you try to format an empty string, you'll get an odd result

```
$return = JHTML::_('date', '0000-00-00 00:00:00', 'Y-m-d H:i:s');
echo 'Formatted date: '$return;
#Formatted date: -0001-11-30 00:00:00
```

here you can find a link back to the tracker:
http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=26575

**Comment by eddieajau** [comment]
This is a known issue and possible bug in PHP.  Use an if test on the date to check that it is valid {usually intval($date) will do} before using the JHtml method.
