### ISSUE TITLE
Make all unit tests pass with deprecated code removed

### ISSUE THREAD

**Issue by realityking** [joomla/joomla-platform#240]
I started keeping a branch with some of the deprecated code removed to get a feeling how much it is and I thought it would be a good idea to run unit tests on that to see what breaks. So here goes the first one, I'm sure more will turn up once this one is fixed:

Fatal error: Call to undefined method JXMLElement::getAttribute() in /Applications/MAMP/htdocs/joomla-platform/libraries/joomla/form/rules/options.php on line 43

**Comment by eddieajau** [comment]
Fixed in https://github.com/joomla/joomla-platform/pull/292

**Comment by realityking** [comment]
Next error:
Fatal error: Call to undefined method JRegistry::getValue() in /Applications/MAMP/htdocs/joomla-platform/libraries/joomla/log/log.php on line 251
