### ISSUE TITLE
Suggestion for improved error handling during extension installation (Joomla issue tracker id=25676)

### ISSUE THREAD

**Issue by jmcameron** [joomla/joomla-platform#246]
(From http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=25676)

In line 1235 of libraries/joomla/installer/adapters/component.php, there is the
following line (when building a menu):

```
// If the install fails, exit and roll back changes
if (!$table->setLocation(1, 'last-child') || 
    !$table->bind($data) || 
    !$table->check() || 
    !$table->store()) {
     // Install failed, rollback changes
     return false;
     }
```

I suggest changing this to:

```
// If the install fails, exit and roll back changes
if ( !$table->setLocation(1, 'last-child') ) {
    JError::raiseWarning(1, $table->getError());
    }
if ( !$table->bind($data) ) {
    JError::raiseWarning(1, $table->getError());
    }
if ( !$table->check() )  {
    JError::raiseWarning(1, $table->getError());
    }
if ( !$table->store() ) {
    JError::raiseWarning(1, $table->getError());
    }
```

Each of these functions produces very useful error messages which are being discarded the way the code is current written.   This addition would be very helpful to help extension developers debug their component installation problems. 

-Jonathan

P.S. Although Sam feels that this is not the long-term approach he advocates for error handling, I still feel that something needs to be done on this particular section of code sooner rather than later to make it easier for extension developers to debug their code!

I am willing to do a fork to change this as I suggested above as in interim measure until a more effective long-term solution is implemented.  Just let me know.  -Jonathan
# Follow up comments from the Joomla issue tracker:

Submitted By: Samuel Moffatt
Adddate: 2011-04-24 21:37:31
You don't need to split it out though, just add the JError::raiseWarning before the return as it stands now. The  || will halt execution at the first failure and drop into the false. All you're doing is duplicating what it does now.

In general with 11.1 we're moving towards more logging than the way JError behaves at the moment. I'm not quite sure what that looks like for the installer as it already has a message infrastructure in place of its own that you could set.

---

Submitted By: Andrew Eddie
Adddate: 2011-08-12 21:44:32
Please raise this issue on the Joomla Platform issue tracker
(https://github.com/joomla/joomla-platform/issues), including a link back to
this page, or fork the Platform, make the appropriate changes and issue a pull
request.

Thanks.  Closing issue.

---

Submitted By: Elin Waring
Adddate: 2011-08-14 09:09:46
I'm going to leave this closed since Sam seems to be suggesting a different
approach that could perhaps be solved partly with documentation.

**Comment by elinw** [comment]
The main concern i have (not really knowing about this piece of code) is that JError is deprecated and i think you should be using the newer APIs. You might want to log the errors also.

**Comment by jmcameron** [comment]
As far as I can tell, none of the code in libraries/joomla/installer has been converted to the new exception-style error handling.  So the question is: shall we wait for the conversion to exception-style error handling and fix this then, or do it now in the old style and then update it later when the exception-style error handling is implemented?  I guess part of the answer to this is whether Joomla will get a fresh update from the Platform before the installer code is expected to be converted to the new error handling approach?  If so, then I think it is worth fixing this now.  If not, then it makes sense to wait.

**Comment by elinw** [comment]
Step by step that's the way, removing deprecated code is going to go library by library but we shouldn't be adding to it.  I'd like to hear more from Sam too.

**Comment by pasamio** [comment]
No my view is that doing:

// If the install fails, exit and roll back changes
if (!$table->setLocation(1, 'last-child') || 
    !$table->bind($data) || 
    !$table->check() || 
    !$table->store()) {
     // Install failed, rollback changes
     JError::raiseWarning(1, $table->getError());
     return false;
     }

is the same as what you propose except instead of adding five lines, we add one. I also suggest that the general direction is towards using JLog and that since we've done 1.7 that it'd be nice to go that way though potentially it could work through the internal installer message notification system. I don't think it is reasonable to throw an exception here as we already have a defined interface that works, we just want to log the error ;)

**Comment by jmcameron** [comment]
Hi Sam.  Yes I think just adding the JError::raiseWarning() as you suggest here should be an adequate interim measure.  The problem.  The problem with the old code was that not error was raised at that point and it just returned false and the error message associated with the $table was lost.  If you raise the error as in your code snippet, the the first failing case will raise the error with the associated error message.   By the way, is there any reason to return false if you raise an error/warnng?

**Comment by elinw** [comment]
Would you please use JLog and a $msg rather than using JError.

**Comment by jmcameron** [comment]
Could you point me to an example of this?  The only thing that I see in Platform currently that seems to be what you want is in libraries/joomla/database/database.php (around line 280) that looks like this:

```
// Legacy error handling switch based on the JError::$legacy switch.
// @deprecated 12.1

if (JError::$legacy)
{
    // Deprecation warning.
    JLog::add('JError is deprecated.', JLog::WARNING, 'deprecated');
    JError::setErrorHandling(E_ERROR, 'die');
    return JError::raiseError(500, JText::sprintf('JLIB_DATABASE_ERROR_LOAD_DATABASE_DRIVER',  $options['driver']));
 }
else
{
    throw new JDatabaseException(JText::sprintf('JLIB_DATABASE_ERROR_LOAD_DATABASE_DRIVER', $options['driver']));
 }
```

If this is what you want, we will need to add an appropriate exception class, etc.

**Comment by elinw** [comment]
Exactly just to the JLog and I would say use category installation unless someone has another suggestion..
 JLog::add('Whatever you want.', JLog::WARNING, 'installation');

**Comment by jmcameron** [comment]
Ok, I forked the platform and fixed this code to read:

```
    if (!$table->setLocation(1, 'last-child') || !$table->bind($data) || !$table->check() || !$table->store())
    {
        // Install failed, warn user and rollback changes
        JLog::add($table->getError(), JLog::WARNING, 'installer');
        if (JError::$legacy)
        {
            // Deprecation warning.
            JLog::add('JError is deprecated.', JLog::WARNING, 'deprecated');
            JError::raiseWarning(1, $table->getError());
        }
        return false;
    }
```

Not sure if this is exactly right. I thought that throwing an exception was not the right answer since we want to be able to recover to run postflight, etc.  So I settled on just using the log message as shown.   I tested this in my Joomla 1.7.0 test set up (just replacing this 'if' statement in the older code) and it worked fine. I was able to get a more fine-grained error message using it.    The Platform PHPUnit tests are not affected by this change.  I'm guessing that install failures are not tested.    I did not do any of the other error messages because I wasn't sure how most of them are supposed to operate. 

If everyone is happy with this, I'll do a pull request.

   -Jonathan

**Comment by elinw** [comment]
You don't want to log that Jerror is deprecated that will happen already whenever JError is used.

**Comment by eddieajau** [comment]
Why wouldn't you just abort with a message, eg:

$this->parent->abort($table->getError());
return false;

??

**Comment by jmcameron** [comment]
Hi Eddie,

Not sure exactly what 'abort' does.  If it REALLY aborts and goes directly to an error message, I think that may not be what you want to do here since it would not allow the installer to unroll the failed install...

This is what the latest code in the pull request looks like:

```
if (!$table->setLocation(1, 'last-child') || !$table->bind($data) || !$table->check() || !$table->store())
{
    // Install failed, warn user and rollback changes
    JLog::add($table->getError(), JLog::WARNING, 'installer');
    if (JError::$legacy)
    {
        JError::raiseWarning(1, $table->getError());
    }
    return false;
}
```

I'm happy to change this error handling to what ever makes sense.   I'm kind of caught between the desire to improve the error handling now and the desire of many to make sure any changes match the future direction of error handling.    The only example I could find of something that looked like the future direction of error handling was in libraries/joomla/database/database.php.    I modified it appropriately with some suggestions from Elin and my cut in the pull request it is now.  I'm willing to change it if you give me an example to copy. 

It would be very helpful to have a page on docs.joomla.org showing what we should be doing for error handling in 1.7 and beyond since JError is being deprecated...

-Jonathan

**Comment by eddieajau** [comment]
Yeah, we'll have to have a think about the transition.  The plan is not to drop JError until 12.1 which is the version that Joomla 3.0 will be using.

**Comment by jmcameron** [comment]
Hi Eddie,

What would you like me to do about this?   Leave it as it is in my August 20 post above?  If so, I think this patch can be merged in.  If not, let me know how you would like me to update it.

-Jonathan

**Comment by eddieajau** [comment]
I think the raise-warning is the easiest of a bad bunch of options.  However, I'd remove the legacy check for now.  If it's to be included it should really have the following form:

```
if (JError::$legacy)
{
    JError::raiseWarning(1, $table->getError());
}
else
{
    throw new JInstallerException($table->getError());
)
```

but since we don't have robust exception support yet, we'd loose any visual cue for the error.

**Comment by jmcameron** [comment]
From your comments on the pull request, I'll update this to do just the raiseWarning and submit a new pull request.

**Comment by jmcameron** [comment]
This issue has apparently been resolved.  The new code reads:

if (!$table->setLocation(1, 'last-child') || !$table->bind($data) || !$table->check() || !$table->store())
{
    // Install failed, warn user and rollback changes
    JLog::add($table->getError(), JLog::WARNING, 'jerror');
    return false;
}

Therefore I'm closing this.
