### ISSUE TITLE
Error on unit tests

### ISSUE THREAD

**Issue by jonnsl** [joomla/joomla-platform#261]
I'm currently getting this error while trying to run the unit tests against the master branch 
Fatal error: Class 'JTable' not found in /home/jonnathan/www/joomla-platform-fork/libraries/joomla/database/table/user.php on line 20

**Comment by eddieajau** [comment]
I don't have any problem running the tests.

**Comment by realityking** [comment]
Since no follow up and no one else reported this issue in the last 6 months I'm going to close this issue.
