### ISSUE TITLE
$obj reference in JTable canDelete

### ISSUE THREAD

**Issue by AmyStephen** [joomla/joomla-platform#284]
https://github.com/joomla/joomla-platform/blob/master/libraries/joomla/database/table.php#L1419

Looks like old code - there is no $obj defined in the canDelete method

**Comment by eddieajau** [comment]
I'm guessing it should be $row->$k.  In 1.5 it used to be
    if (!$obj = $this->_db->loadObject())

Do you want to have a stab at making a pull request on that and just double checking that code actually works?

Thanks in advance.

**Comment by eddieajau** [comment]
Amy, you up to doing a simple patch for this, or will I put it out on the mailing list for someone to do?

**Comment by AmyStephen** [comment]
If you can wait until after this weekend, I'll take care of it. Right now, I'm slammed so understand if you find someone else.

**Comment by eddieajau** [comment]
No great hurry - it's just an easy one to get out of the way :)  Obviously not many people use the feature.

**Comment by eddieajau** [comment]
Any luck getting that pull request together?

**Comment by eddieajau** [comment]
Any update?

**Comment by AmyStephen** [comment]
No update Andrew - didn't mean to close the issue, though. Maybe best to put it out for others, as you suggested earlier. I've been very busy and it's not subsiding.

**Comment by eddieajau** [comment]
Thank you. That's all I needed to know. Will do.

**Comment by andreatarr** [comment]
fixed and committed https://github.com/joomla/joomla-platform/pull/435#issuecomment-2437517

**Comment by AmyStephen** [comment]
Going to close this since Andy has it fixed.

Thanks Andy.
