### ISSUE TITLE
[CMS Issue Tracker #26606]  Extension type "file" install fails with using folders

### ISSUE THREAD

**Issue by at-dro** [joomla/joomla-platform#286]
I was told in the JBS mailing list that this should be in this tracker instead of the CMS tracker, so I copied it from http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=26606 - I hope it's correct that way.

Some example files are available in the CMS tracker item.

--copied description below--

I have an extension of type "file" (<extension
version="1.7" type="file">), which uses files and
folders within the "fileset" tag.
Like this:
&nbsp;&nbsp;&nbsp;&lt;fileset>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;files target="somefolder">
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;file>somefile&lt;/file>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;file>someotherfile&lt;/file>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;folder>somesubfolder&lt;/folder>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/files>
&nbsp;&nbsp;&nbsp;&lt;/fileset>

In the extension zip archive the two files and the somesubfolder (with some
content) are in the same folder as the xml manifest.

When trying to install the extension it will always raise a notice on
"[path to joomla]/somefolder/somesubfolder" existing already. The
message is 'JLIB_INSTALLER_ERROR_FILE_EXISTS', which is raised in
JInstaller::copyFiles() in libraries/joomla/installer/installer.php:1352. No
matter how often the folder is deleted manually, it will always exist before
the copyFiles method is called.

I'll provide you with an overview of my debugging steps so you can either
confirm or falsify my result.
I was able to trace this bug back to the file adapter located in
libraries/joomla/installer/adapters/file.php. The install method makes sure all
target folders exist, and creates them if not (lines 142-168 of file.php). The
list of folders is built in the method populateFilesAndFolderList in the same
class/file. In lines 592-602 the folder tree of the target attribute is added
to the list, which works fine.
Starting in line 618 the files to copy are added to an array. I believe the bug
is located this section: In line 628 the filename is added to the folderlist, if
it's a folder (by checking the tagname in line 626). All folders in the
folderlist array are created in line 152 of file.php. The main installer class
doesn't need this folder, as it's gonna copy the whole folder, though.

The bug seems to be removed by just commenting/removing line 628 of file.php
(and also 627, as it becomes dead code).

Doing this works fine as far as I tested so far.

**Comment by elinw** [comment]
Do you want to just send a pull request for this? Then you will probably get more feed back.

**Comment by eddieajau** [comment]
The installer is something we want to take out of the platform so while, yes, the code that needs to be fixed will be in the Platform currently, the CMS is the only one using and to determine a fix.  Once a patch is reviewed by the JBS, make a pull request here.  Thanks.
