### ISSUE TITLE
[CMS Issue Tracker #26607] Extension type "file" uninstall: Folders remain undeleted

### ISSUE THREAD

**Issue by at-dro** [joomla/joomla-platform#287]
I was told in the JBS mailing list that this should be in this tracker instead of the CMS tracker, so I copied it from http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=26607 - I hope it's correct that way.

--copied description below--

When uninstalling an extension of type "file", folders listed in the
manifest file won't be deleted (for example like in previous bug
http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=26606
- actually fixing the previous one is required to be able to get a fully
  uninstallable extension). This behavior makes it impossible to reinstall the
  extension without deleting the folders manually.

Deleting the files and folders listed in the manifest file is handled in
libraries/joomla/installer/adapters/file.php lines 466-505, to be more specific
starting in line 485. Files are deleted instantly, folders are added to an array
to be deleted later. Anyway, before the folder gets deleted it is checked
whether it's empty (line 500-503). As the files in it are never deleted (which
is impossible, as they are not listed anywhere) the folders will remain.

A quick fix would be to delete the folder in any case, without checking if it's
empty. This behavior would match e.g. the removal of a component, where both the
admin and site folders are removed completely.

**Comment by eddieajau** [comment]
Closing as this is marked as a known issue in the CMS tracker.
