### ISSUE TITLE
Make JDatabaseQueryElement and JDatabaseQuery inherited from JObject

### ISSUE THREAD

**Issue by Denitz** [joomla/joomla-platform#291]
We can't change the query elements and get information about the current query.
For example, I need to check if a specific table was joined - but can't read protected variable $join.
Inheritance from JObject will allow to use get() and read/modify data with set().

**Comment by eddieajau** [comment]
Hi Denitz

A magic get was added to JDatabaseQuery back in June, and made it into 1.7.

https://github.com/joomla/joomla-platform/blob/master/libraries/joomla/database/databasequery.php#L380

Hope this helps.

**Comment by Denitz** [comment]
Yes, now I can check if a table was joined.
But I can't remove it from join.
Can we have __set here?

Otherwise we are forced to use clear('join')  and next rejoining all tables

**Comment by eddieajau** [comment]
Hrm, I guess that would be ok, but the magic set would need to do some type checking.  In other words, if it's a field that is expected to be a JDatabaseQueryElement isn't, it should probably throw an exception.  Another option is to add JDatabaseQueryElement::remove so you can remove selected joins, eg:

$query->join->remove($index)

Either way, make sure the unit tests are updated in any pull request.  Thanks in advance.

**Comment by Denitz** [comment]
and what about returning by reference?
public function &__get($name)

**Comment by eddieajau** [comment]
Objects are returned by reference in PHP 5.

**Comment by Denitz** [comment]
Sure :)
But JDatabaseQuery->_join property is array of JDatabaseQueryElement objects, I unset the object element but original protected _join array will stay the same.

**Comment by eddieajau** [comment]
Oh, you are right. It's obviously been a long day.  I'd prefer a plain _ _set (forget what I said about type checking) to compliment _ _get.  I actually don't know if &_ _get would work but my gut feel is it's not good practice.

Having said that, manipulation of queries like that is at your own risk!

**Comment by Denitz** [comment]
__get would be excellent, but:
What is the purpose of casting properties as protected in this case? We would still are able to modify them :)
Why not to use public scope and don't use magick methods? This is just a JDatabaseQuery class which should allow flexibility and scalability, but not a class of bank credit card :)
I don't see any sense in protected vars for the scalable framework.

**Comment by eddieajau** [comment]
It would help if you try to communicate what you are trying to achieve and why.  In the absence of that, the purpose of the protected properties is so you can't mess with them outside of the published API.  I'll turn the question around and ask why should I let your plugin (presumably?) alter queries in my extension?

**Comment by Denitz** [comment]
ok, but here is another question - how can I alter queries in my own extension.
My component creates a complex query which is next used to get count and get rows
Count doesn't require few joins, so I want to remove them from query.

**Comment by eddieajau** [comment]
Ok, thanks for that. Now I have some context.

So far my testing indicates that for a "count", clearing the select and then making it $query->select('COUNT(a.id)') or similar has a huge impact.  So does clearing the ordering clause.  I've found less improvement reducing joins less.  At this stage my thinking is to either leave the joins, or to complete rebuild the joins tuned for the total counting.  I'm working with some very large data sets and that seems to be working well.

A longer term solution is to look at something like "named" query elements so that you can just excise specific query elements, but that still needs some thought.

That's my current thinking anyway.

**Comment by Denitz** [comment]
Thanks for the info, I already use $query->clear('select')->clear('order')->select('COUNT(*)').
So Joomla platform won't have the normal way to removed joined table, other than getting the ->_join property, than manually parsing all _join elements and adding them back to the query after ->clear('join')?

**Comment by eddieajau** [comment]
Personally I think the effort to scan through the joins to work out which one is which, and then splice them back is roughly equal to the effort in rebuilding the joins that only apply for the count.  Usually, you'd be removing more joins (if not all) than you'd be keeping.  That's my experience anyway.

**Comment by pollen8** [comment]
in my experience, if you are only using mySQL, doing count on complex joined data gives 'interesting' results. I now tend to do:

$db = JFactory::getDbo();
$query = $db->getQuery();
$query = $db->getQuery(true);
$query->select('SQL_CALC_FOUND_ROWS, field')->from('tbl');
$rows = $db->loadObjectList();
$db>setQuery("SELECT FOUND_ROWS()");
$count = $db->loadResult();
