### ISSUE TITLE
CMS TrackerItemEdit&tracker_item_id=26694 timezone fatal error

### ISSUE THREAD

**Issue by elinw** [joomla/joomla-platform#293]
http://code.joomla.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=26694

I wanted to bring this to people's attention since this was a patch that was committed in February to the trunk but is not showing in the platform or trunk now. Further, the code has just been left as commented (as in the original commit).  Not really sure if this was a good solution because I don't know if even though the code is not used in the CMS it might not be used by some other application in which case it would be better to make it conditional.

**Comment by eddieajau** [comment]
How do you reproduce the problem?

**Comment by elinw** [comment]
You have to go read the old  reports, people say that it happens if the user time zone is changed. 
You can see there was quite a bit of back and forth on the original issue report.
http://code.joomla.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=24532 where in the comments someone says how to reproduce. 

Submitted By: Alex Yap
Adddate: 2011-01-24 22:49:57
You can replicate the said error but calling the JFactory getDate function by
passing in an time off set parameter. In Joomla 1.6 the time off set parameter
is suppose to pass in as an object of DateTimeZone();

For example.

$userTZ = $jConfig->get('offset');
$newTZ  = new DateTimeZone($userTZ);

$date   =& JFactory::getDate('now', $newTZ);

Anyway I know we aren't supposed to bring issues over here until they are patched in the cms, but it just seemed odd to me and also I'm not sure how the original commit was lost, I guess somewhere in the merging back and forth.

**Comment by eddieajau** [comment]
https://github.com/joomla/joomla-platform/pull/294

Root cause is that whoever fixed 1.6 didn't understand the actual problem.
