### ISSUE TITLE
JDatabaseQuery incorrectly building DELETE query

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-platform#300]
In doing conversion work on Finder, I've run into an issue with JDatabaseQuery building DELETE queries incorrectly.  The index function is assembling the below query as "DELETE FROM t.*,`jos_finder_taxonomy` AS t...", causing the index process to error out.

Unless I've misunderstood based on how I've read the code, I would expect the query to be sent as "DELETE t.\* FROM `jos_finder_taxonomy` AS t..."

$db = JFactory::getDBO();
$query = $db->getQuery(true);
$query->delete('t.*');
$query->from($db->quoteName('#__finder_taxonomy').' AS t');
$query->join('LEFT', $db->quoteName('#__finder_taxonomy_map').' AS m ON m.node_id = t.id');
$query->where($db->quoteName('t.parent_id').' > 1');
$query->where($db->quoteName('m.link_id').' IS NULL');
$db->setQuery($query);
$db->query();

**Comment by eddieajau** [comment]
Try removing the from method and just having:

$query->delete($db->quoteName('#finder_taxonomy').' AS t');

**Comment by mbabker** [comment]
Still getting SQL errors about what looks to be the AS t part, but it looks a bit more correct now.

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AS t LEFT JOIN `jos_finder_taxonomy_map` AS m ON m.node_id = t.id WHERE t.parent' at line 2 SQL=DELETE FROM `jos_finder_taxonomy` AS t LEFT JOIN `jos_finder_taxonomy_map` AS m ON m.node_id = t.id WHERE t.parent_id > 1 AND m.link_id IS NULL

**Comment by eddieajau** [comment]
Ok, I think that is a normal SQL error.  The trick with delete() is that it takes the table name.

I'll close the issue for now but if you find something wrong in the future please let me know.
