### ISSUE TITLE
DateTime::setTimezone error in tests

### ISSUE THREAD

**Issue by tampe125** [joomla/joomla-platform#314]
hi, so for i still get 4 errors when i run the tests:

```
1) JTableNestedTest::testStore
DateTime::setTimezone(): Can only do this for zones with ID for now

2) JTableNestedTest::testPublish
DateTime::setTimezone(): Can only do this for zones with ID for now

3) JTableNestedTest::testGetRootId
DateTime::setTimezone(): Can only do this for zones with ID for now

4) JLogEntryTest::testDefaultValues
DateTime::setTimezone(): Can only do this for zones with ID for now
```

the error is in the JDate::format function.
infact at line 338 there is this method

```
parent::setTimezone($this->_tz);
```

i made some tests, but it seems that these errors happear only on those tests, overall it's working fine.
any help?

**Comment by eddieajau** [comment]
Update from master and those tests errors should go away.  That problem was fixed in one of yesterday's builds.
