### ISSUE TITLE
Cache calls function "getHeadData" which is not defined in "JDocumentRaw" 

### ISSUE THREAD

**Issue by Bakual** [joomla/joomla-platform#327]
If you use the raw document type in your component and have the caching turned on, it will generate a fatal error because it tries to call the method "getHeadData" which is of course not defined in JDocumentRaw:

"JDocumentRaw::getHeadData() in /srv/www/htdocs/joomla16/libraries/joomla/cache/cache.php on line 502"

I don't know if I can work around this issue on my (component developer) side or if this better should be fixed in the library by making a check if this method exists.

Changing line #501 in libraries/joomla/cache/cache.php from:

```
if ($loptions['nohead'] != 1) {
```

to:

```
if ($loptions['nohead'] != 1 && method_exists($document, 'getHeadData')) {
```

would probably solve the issue.

**Comment by eddieajau** [comment]
Yeah, I think that's the best of a bad bunch of options.  That area of the code is way too tightly coupled to the CMS and needs to be pulled out one day anyway.

If you could make a pull request with that change (it's line 567 in the platform file), or ask if someone else could do it for you, that would be great.

Thanks!

**Comment by Bakual** [comment]
I have no clue how to create such a pull request, so if someone can tell me how to do it I can try. Or someone else can do it, I don't care for the credits :-)

**Comment by eddieajau** [comment]
Basically the steps are fork the joomla-platform, clone it to your computer, edit file, commit the changes, push the changes back to your github fork, then issue a pull request against our staging branch.

There a bit of setup information here: http://docs.joomla.org/Working_with_git_and_github
and also in the wiki here https://github.com/joomla/joomla-platform/wiki

**Comment by Bakual** [comment]
Seems like it worked, but it openend a new issue for it? Should have probably named it the same or so. 
Thanks for the explanations. I didn't have to download it to my computer, I could edit it in the webbrowser.

**Comment by realityking** [comment]
This issue appears to have been fixed.
