### ISSUE TITLE
jimport() problem

### ISSUE THREAD

**Issue by Denitz** [joomla/joomla-platform#334]
I started receiving the error in my component:
Fatal error: Cannot redeclare class JCacheController in /libraries/joomla/cache/controller.php on line 20

This was also reported from other users:
http://forum.joomla.org/viewtopic.php?p=2591974

After investigation I found the issue: class JCacheControllerCallback calls:
jimport('joomla.cache.controller');

The issue is that actually JLoader::import() registers class JController but not JCacheController to \libraries/joomla\cache\controller.php, so cache controller class is loaded again once the JController is required.

**Comment by eddieajau** [comment]
Thanks Denitz. I think the easiest think is to just make a pull request removing the jimport line from the callback controller.

**Comment by aaronschmitz** [comment]
This appears to have been resolved.
