### ISSUE TITLE
Optimizing JMenu::getItem()

### ISSUE THREAD

**Issue by Denitz** [joomla/joomla-platform#335]
I think that better have this method as:
public function &getItem($id)
{
    if (isset($this->_items[$id])) {
        return $this->_items[$id];
    }

```
$result = null;
return $result;
```

}

**Comment by eddieajau** [comment]
Why is that better?  I'd probably just go for a ternary operator myself, eg:

```
return isset($this->_items[$id]) ? $this->_items[$id] : null;
```

Thoughts?

**Comment by Denitz** [comment]
agree!
