### ISSUE TITLE
loadnextrow and loadnextobject do not iterate

### ISSUE THREAD

**Issue by brbrbr** [joomla/joomla-platform#339]
I would expect loadnextrow and loadnextobject  in database.php to walk tru the result set.

However the cursor is reset  for each call to the function ( like loadrow returns the first row indeed)

**Comment by eddieajau** [comment]
I'd say the methods need to be changed to use $this->cursor.  Are you able to make the required code changes and make a pull request, or do you need help with that?

**Comment by brbrbr** [comment]
Whether it uses the static or $this it will need to check for a valid cursor as well.

I'm not familiar with qit, I have a fork with a patch ( if ( $cursor === null ) {} added. 
Just hit the 'pull request' button or RTFM ?

**Comment by elinw** [comment]
Click pull request, then change the destination from master to staging (just click on the block where it says master and start typing, you'll get a drop down).

**Comment by brbrbr** [comment]
ok,

i hope i didn't mess up the repository to much

**Comment by eddieajau** [comment]
Going to close this issue since we have a pull request in the pipeline.
