### ISSUE TITLE
JFormFieldMedia incorrect folder processing (fix provided)

### ISSUE THREAD

**Issue by piotr-cz** [joomla/joomla-platform#342]
test instructions:
com_media with configured 'image_path' as a 2+level directory (ie. media/Pliki).
bug doesn't occur when image_path configured to 1-level directory (images)

details:
JFormFieldMedia has a hardcoded method to compute $folder variable by stripping first directory in the image path value and a filename.
$folder variable is then passed in a query 'folder='.$folder when calling com_media component

fix:
file libraries/joomla/form/fields/media.php, line 97: replace
array_shift($folder)
by
array_diff_assoc( $folder, explode('/', JComponentHelper::getParams('com_media')->get('image_path', 'images')) );

this will strip configured image_path in the $folder array
sorry for not adding Pull request, I'm in a process of learning git

**Comment by elinw** [comment]
Puotr. why don't you use the github web ui to edit the file and send a pull request for this change?

**Comment by piotr-cz** [comment]
Thanks elinw, I just did so: https://github.com/joomla/joomla-platform/pull/728

**Comment by realityking** [comment]
Issue has been fixed a month ago with the above pull request.
