### ISSUE TITLE
Language Files lost during tar.gz Package extract

### ISSUE THREAD

**Issue by AmyStephen** [joomla/joomla-platform#350]
When installing JFoobar using the tar.gz option, it was discovered that the language files located in:

media/components/administrator/components/com_jfoobar/media/components/site/components/com_jfoobars/language/en-GB

and 

media/components/components/com_jfoobar/media/components/site/components/com_jfoobars/language/en-GB

are not copied to the destination (which is the same on the destination site, absent the media/components portion of the path.)

When the tar.gz file is manually unzipped into the tmp folder => it can be installed using the "Install from Directory" -- the problem only manifests when installing using the tar.gz file directly.

Also - I was able to isolate the problem to the JArchiveTar::extract method, it doesn't appear that these files are recognized as type of file or folder in the loop. But, I'm stumped as to why.

The JFoobar tar.gz can be used to demonstrate this problem.  https://github.com/Niambie/jfoobar

The issue was reported https://github.com/Niambie/jfoobar/issues/6

**Comment by eddieajau** [comment]
So, first off I can confirm the issue.  What appears to happen is the unpacking of the tar.gz falls apart - all the files are there, just looks like a cyclone has hit it.  OSX was, however, able to correctly unpack the archive.  I rezipped and command line tar zipped and both new packages worked ok.  So, my conclusion is that git hub makes the tar.gz files in a slightly peculiar way which manifests a bug in our unpacking code.  Given that command line archiving works, I think we'd chalk this up to a known issue for now until someone has the time and patience to trace through why github's tar.gz files are slightly peculiar.

I recommend you use phing or similar to make you packages.  You can find an example that I use often here:

https://github.com/eddieajau/artof-google-mini/blob/master/build/build.xml

**Comment by AmyStephen** [comment]
Probably best to see if there are other issues.

I added a warning to our readme and included your resource for packaging. Thanks for the resource - should be very helpful to folks.

Going to close this issue for now.

**Comment by eddieajau** [comment]
Ok, keep us posted.
