### ISSUE TITLE
11.2 JPlatform CLI mode. Error using JFile:: delete if the file does not exist.

### ISSUE THREAD

**Issue by zian974** [joomla/joomla-platform#365]
Hello,
Using JPlatform 11.2 in CLI mode, I have the following error if the file to delete does not exist:
PHP Fatal error: Class 'JRequest' not found in / home / web / www / JPlatform / libraries / joomla / session / session.php on line 453
And if I include the class JRequest (I'm in CLI mode ???), errors are displayed in the terminal with all the call stack.

Ok, I have to check if the file is present but it's still a little annoying.

**Comment by eddieajau** [comment]
Could you post a snippet showing how you are using JFile::delete (use gist if you like)? I suspect it's something to do with the FTP layer we have in there (_sigh_). Thanks.

**Comment by zian974** [comment]
Bonjour, 

you can find the code snippet that i use here: git://gist.github.com/1231162.git (https://gist.github.com/1231162).
The use of JFile:: delete is on the line 161.
Sorry, but I left the entire script.

And What about the issue n°364.
If a field of a table has already received a value, it is impossible to assign a new value to null afterwards.

**Comment by aaronschmitz** [comment]
I certainly can't reproduce this.

**Comment by LouisLandry** [comment]
JRequest has been decoupled from JSession which was the symptom here.  If you run into this issue again please feel free to re-open or open a new issue.  Thanks!
