### ISSUE TITLE
Session id column too short

### ISSUE THREAD

**Issue by nibra** [joomla/joomla-platform#372]
Since MD5 is no longer recommended for cryptographic use, some hosts use the SHA-1 algorithm, producing a longer session ID. The Joomla DB schema should be changed to prevent this - the assumption that the session id is always 32 characters in length is false. With PHP 5.3 there are far more hash functions available to generate the session id. And people can use their own method for generating session ids instead of PHP's built in functionality. Even 40 bytes is not enough - I had a case, where the hash was 52 bytes long.

So changing the column length for sessionid in #__sessions to 64 bytes should solve the problem.

**Comment by elinw** [comment]
The db schema is actually part of the application not the platform.
If you checkout the CMS Trunk you will see that the size of the session column has already been changed for 1.7.1.

**Comment by nibra** [comment]
Great news, thank you!

**Comment by madhurad** [comment]
I am using 1.7.3 version and facing this issue, changed from 32 to 64 bytes still issue is there.

**Comment by nibra** [comment]
Ca n you determine, which hashing algorithm your installation uses? I've heard of other installations that needed more than 64 bytes, and worked well witch 128 bytes.
