### ISSUE TITLE
JFile::write() uses $buffer by reference

### ISSUE THREAD

**Issue by Denitz** [joomla/joomla-platform#386]
Why ?
public static function write($file, &$buffer...

We can't have this code:
JFile::write('somefile.php', 'text');

Fatal error: Cannot pass parameter 2 by reference...

**Comment by mahagr** [comment]
I've also hit this "feature" when trying to create dummy html file into empty directory. It works perfectly in J!1.5 but not in J!1.7, which makes the function not to be backwards compatible -- and there's no documentation that the API has changed.

**Comment by eddieajau** [comment]
The reference is probably there to save on memory (JFile is notorious for consuming it).
