### ISSUE TITLE
JArchiveZip::_extractNative() -- invalid zip_open() check

### ISSUE THREAD

**Issue by polymorphm** [joomla/joomla-platform#407]
good day!

was missed in the code `else {...}` block

...so if ZIP-file was opened is _not_ correct, then still will be `return true;`

I think -- need to do:

https://gist.github.com/1253521#file_0001_fixed_zip_open_fail_actions.patch

or

https://gist.github.com/1253520#file_0001_fixed_zip_open_fail_actions.patch

thanks in advance!

**Comment by elinw** [comment]
Is this a variation of the same issue that is in the CMS tracker? 
 http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=26906

**Comment by polymorphm** [comment]
@elinw, yes. thanks! :)

**Comment by elinw** [comment]
Is this issue impacted by the check for native support that was added?

**Comment by aaronschmitz** [comment]
https://github.com/joomla/joomla-platform/pull/938

**Comment by realityking** [comment]
Closing as fixed. Thanks!
