### ISSUE TITLE
loadElement only includes first matched element file. Problem with multiple elements with same main name.

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-platform#455]
Sorry for the long explanation here, but it probably makes the problem clear enough:

When having admin views like the module edit page, you have the JForm elements on the right. These are different fields.
The different xml files that are used to create these (some of module itself, some of core, etc) can have an addpath to include extra field files.

So far so good. But, if there are field files with the same file name, things go haywire...

Now there is a possibility to call on these field types with prefixes, to prevent duplicate class names.
Like in my case I have a type="nn_categories"
This will act on the class JFormFieldNN_Categories in the file categories.php in the addpath location. Note, it doesn't look for nn_categories.php but for categories.php

So my thought is that the function that loads the files from the different addpaths shouldn't stop at the first filename that matches (categories.php), but should look for the file that actually has the correct classname (JFormFieldCategories vs JFormFieldNN_Categories vs JFormFieldXXX_Categories)

So there is a problem when 2 extensions (plugins/whatever) are involved in creating the form.
Each with their own addpath and with their own extra field files.
So the first could use type="a_categories" and the second uses type="b_categories".

However, Joomla only loads the first categories.php. So only the first JFormFieldA_Categories is initialized. And not the second  JFormFieldB_Categories - causing all b_categories fields to default to a default text field.

Essentially I think the problem is in file: \libraries\joomla\html\parameter.php in the loadElement method.

Instead of looping through all dirs and including all files that match (maybe double checking for duplicate classnames), it simply does a:
JPath::find($dirs, $file)
Which returns the path of the first file that matches....

It should do a while loop through the dirs, checking if the required class exists in the condition... Or whatever better solution there is...

**Comment by LouisLandry** [comment]
Hi Peter, interesting problem.

I'm not sure I'm clear on it though, because you are referencing two classes that don't really have a relationship with one another.  `JForm` and `JParameter` don't share any members or ancestry.  If there is a problem with `JForm`, it really (to the best of my knowledge) couldn't be caused by something in `JParameter`.

Additionally, I don't know that we want to really perform any modifications to a deprecated class like `JParameter`.

Finally, couldn't you solve your problem by having your class setup with the autoloader by using `JLoader::register();`?  If your class is already available, then it won't even try to search for one.  Simply do something like:

``` php
<?php
JLoader::register('JFormFieldB_Categories', '/path/to/categories.php');
```

Just a thought.

I'm quite aware of the limitations of that JPath::find() logic and is one of the reasons we've included the new JLoader::discover() method in the platform.  Hopefully we can get all of the relevant classes using it sooner rather than later.

**Comment by ghost** [comment]
Yep, my bad. Isn't `JParameter` class.
Problem is in the `JFormHelper` class: /libraries/joomla/form/helper.php
in the `loadClass` method

Same problem as described though. It's using this:

``` php
<?php
    if ($file = JPath::find($paths, strtolower($type).'.php')) {
      require_once $file;
    }
```

So it's simply loading the first file name match it finds, which is not necessarily the right one.

**Comment by ghost** [comment]
PS: The `JLoader::register()` method might be a solution for my own elements. But that still doesn't solve elements of 3rd party extensions.

It is also only a patch over the wound. Not a real solution (if it would work, that is).
You would expect the framework to load the appropriate element file when using different 'complex' names, like `a_categries` vs `b_categories`
When having extensions like modules/plugins, you can't (and shouldn't need to) change the JForm behavior when it is rendering the xml for the edit view, by using `JLoader::register()` stuff...

PPS: I am only a 'frontend scripter', not a 'core coder', so forgive my ignorance and lack of insight.

**Comment by LouisLandry** [comment]
No, I agree with you.  I was giving you a workaround for now.  Ultimately you are correct that the problem needs to be solved more elegantly and at a lower level.  Class loading is something we definitely need to be more consistent on, and I don't think there is any disagreement that it should be handled by JLoader, it is just a matter of when it is all gone through and cleaned up to do so.

**Comment by ghost** [comment]
So any insight on what needs to get done to get this fixed and what time frame...?

**Comment by ghost** [comment]
This probably isn't the best/memory-friendly solution, but it does solve the problem in a simple way.
Could this be implemented as quickfix for Joomla 1.7.3?

``` php
<?php
        // Try to find the class file.
        $type = strtolower($type).'.php';
        foreach($paths as $path) {
            if ($file = JPath::find($path, $type)) {
                require_once $file;
                if (class_exists($class)) {
                    break;
                }
            }
        }
```

This would replace the lines currently in the `JFormHelper::loadClass()`:

``` php
<?php
        // Try to find the class file.
        if ($file = JPath::find($paths, strtolower($type).'.php')) {
            require_once $file;
        }
```

**Comment by LouisLandry** [comment]
I'm generally fine with that provided that it works and we have a unit test that proves that it doesn't cause a regression.  As for your former question I don't know is the best answer I can give you on time frame.

**Comment by ghost** [comment]
So is there anything I can/should do to get that testing rolling?

Looking at the code, it shouldn't influence performance much at all. Only thing it essentially does - with regards to function-steps - is do 1 or more `class_exists()` calls extra. Which - to my knowledge - shouldn't be noticeable.

**Comment by LouisLandry** [comment]
fork the platform, write it up, and send a pull request :)

**Comment by ghost** [comment]
Ok, done :)

PS: Git is still Gobbledeegoo for me.
