### ISSUE TITLE
Unresolved conflict commited

### ISSUE THREAD

**Issue by jonnsl** [joomla/joomla-platform#457]
I think that someone forgot to resolve a conflict before commit
https://github.com/joomla/joomla-platform/blob/staging/libraries/joomla/html/toolbar/button.php#L41

**Comment by eddieajau** [comment]
Yep. Just needs a pull request to clean that up.  The HEAD version
should be kept.

Regards,
Andrew Eddie
http://www.theartofjoomla.com - the art of becoming a Joomla developer

On 23 October 2011 05:00, Jonnathan
reply@reply.github.com
wrote:

**Comment by realityking** [comment]
Has been fixes a while back.
