### ISSUE TITLE
JSimpleCrypt::_hexToIntArray

### ISSUE THREAD

**Issue by AmyStephen** [joomla/joomla-platform#473]
Not sure what to do about this one.  The method returns a value $ai that has not been used. 

Would help fix it but I am not certain how, or if it's a real problem.

**Comment by AmyStephen** [comment]
Two more...

The method _xorString  has a similar issue:

(string) $s1 = implode('', $ac);

And _xorCharString returns $ai;

The _xorString is used in the "Remember Me" login in the Joomla Plugin.

**Comment by Buddhima** [comment]
Hi  AmyStephen,
I can't find JSimpleCrypt class in platform. If the issue is still remaining, can you update the information here?

**Comment by LouisLandry** [comment]
Deprecated and replaced.  In doing so I did go through and clean this up.  Thanks for reporting it though Amy.
