### ISSUE TITLE
combo form field type does not work

### ISSUE THREAD

**Issue by tbela99** [joomla/joomla-platform#531]
The file : libraries / joomla / form / fields / combo.php creates an input text field and a hidden list, however initialization script combobox.js refers to a select element:

 $$('select.combobox').each(function(el){
        Joomla.combobox.transform(el);
    });

**Comment by thatryan** [comment]
I think it is a js issue, the source for 1.5 shows the same type of code generated, and the select list is built out of the text input and ul... I am still trying to figure this out too.

**Comment by okonomiyaki3000** [comment]
I had a fix for this but, since 3.0, the fix no longer works. Selects got fancier in 3.0 and so making this functionality work with them would be a bit of a challenge. I wonder if it's actually worth the trouble or should combo just be removed?
