### ISSUE TITLE
Strict standards: JCache::$_handler as non static

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-platform#557]
When E_STRICT php error reporting is on, I get this error all over the place:
`Strict Standards: Accessing static property JCache::$_handler as non static in ...\libraries\joomla\cache\cache.php on line 420`

**Comment by klas** [comment]
Are you getting this with platform or CMS? AFAIK it was fixed in platform some time ago

**Comment by ghost** [comment]
I am getting this in CMS (J 1.7.3). But seeing this is a framework file, I thought the place to post the issue was here...

**Comment by realityking** [comment]
It is the right place, however since the CMS hasn't catched up to the platform yet you'll have errors in the CMS that are already fixed in the platform.

**Comment by realityking** [comment]
This has indeed been fixed a while ago.
