### ISSUE TITLE
No way to disable useStorage in Jhtml tabs

### ISSUE THREAD

**Issue by thinkeryvin** [joomla/joomla-platform#625]
In the JHtmlTabs class, there is no way to disable the useStorage option used in the tabs.js. When passing 'useCookie=>false' to the JHtmlTabs class, the 'useStorage' option is set to null instead of 'false'. When 'useStorage' is null, tabs.js sets it to true by default. Should it be set to 'false' instead of null?

`$opt['useStorage']           = (isset($params['useCookie']) && $params['useCookie']) ? 'true' : null ;`

Instead, use:

`$opt['useStorage']           = (isset($params['useCookie']) && $params['useCookie']) ? 'true' : 'false' ;`

**Comment by realityking** [comment]
```
$opt['useStorage'] = (isset($params['useCookie']) && $params['useCookie']) ? null: 'false' ;
```

That should work, shouldn't it?

**Comment by thinkeryvin** [comment]
Yeah, either way works - pull request sent with the change to 'true' and 'false':
https://github.com/joomla/joomla-platform/pull/626

**Comment by realityking** [comment]
The above pull request has been fixed 2 moths ago.
