### ISSUE TITLE
Fatal error with JEditor::getButtons

### ISSUE THREAD

**Issue by tbela99** [joomla/joomla-platform#660]
the method [getButtons](https://github.com/joomla/joomla-platform/blob/staging/libraries/joomla/html/editor.php#L443) of JEditor contains code that is unsafe 

the following code test existance of a plugin class but do not care whether of not the class is missing. when 

//if this is not true (the plugin may be missing)
if (class_exists($className))
            {
                $plugin = new $className($this, (array) $plugin);
            }

```
        //this will call onDisplay on NULL
        if ($temp = $plugin->onDisplay($editor, $this->asset, $this->author))
        {
            $result[] = $temp;
        }
```

**Comment by Buddhima** [comment]
Got the solution! I'll fix the issue very soon :)

**Comment by eddieajau** [comment]
Sounds like this has been fixed.  It not re-open or resubmit the issue.
