### ISSUE TITLE
Strict error in cms front-end when cache enabled

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-platform#674]
See http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=27515

Strict Standards: Declaration of JCacheControllerView::get() should be compatible with that of JCacheController::get() in JROOT/libraries/joomla/cache/controller/view.php on line 137

**Comment by eddieajau** [comment]
Known issue.
