### ISSUE TITLE
Jimage info

### ISSUE THREAD

**Issue by romacron** [joomla/joomla-platform#687]
perhaps the filestructure of /joomla/image should be such as in forn
filter.php to imagefilter.php
create an helper.php with 

JImageHelper::addFilterPath('mycomponent_model_imagefilter');

JImageHelper::addMethodPath('mycomponent_model_imagemethod');
developers are able to extends the jimage and jimage filter
with more methods and collective filters

**Comment by LouisLandry** [comment]
So we've adjusted it all to use the autoloader now so it is very easy for developers to add their own filters, etc.  Thanks for the thoughts!
