### ISSUE TITLE
jimage division by zero

### ISSUE THREAD

**Issue by romacron** [joomla/joomla-platform#708]
function prepareDimensions
from line: 665

if ($scaleMethod == JImage::SCALE_INSIDE)
{
$ratio = ($rx > $ry) ? $rx : $ry;
}
else
{
$ratio = ($rx < $ry) ? $rx : $ry;
}
is width or height 0 an error will be produzed

an Idea: 
For Web-development/Administration in many cases i need an image-stack with same width or same height.
this harmonize the visible s for the website user. 

perhaps we can build in an decision "is only one value 0" the image will be resized to the opposite value.

**Comment by Buddhima** [comment]
Isn't it better to be $rx same as $this->getWidth() if $width = 0 and $ry same as $this->getHeight() if $height=0 ?

**Comment by romacron** [comment]
ive seen it on your stage it solves it, think

**Comment by romacron** [comment]
i had reopen'd the ticket
and changed  https://github.com/romacron/joomla-platform/commit/3c28b42057de12075caea03eed171a1072a64895#diff-0

resize actions if they should scale to Edge must have as opposite value $rx  or $ry an 0 not the $this->getWith()
