### ISSUE TITLE
Get all changes from Joomla CMS 1.7 merged into platform.

### ISSUE THREAD

**Issue by LouisLandry** [joomla/joomla-platform#74]
We need to make sure (for this time only) that we merge relevant platform changes from the CMS into the tree to keep things aligned.

**Comment by AmyStephen** [comment]
Louis - will 1.7 be based on 11.2? Is that what this means? (Sorry to be so dense.)

**Comment by LouisLandry** [comment]
This actually means it goes the other way around.  For the 11.2 release of the platform we want to make sure that we account for anything that snuck into the CMS libraries without getting added to the platform.  As for what 1.7 will be based on I suspect it will really be 11.1 with some minor tweaks here and there.  It isn't being dense, things are a little non-normal at the moment, but after we get through august things will be much more settled and clear I think.

**Comment by AmyStephen** [comment]
k - thanks Louis. I think I am finally catching up here. Exciting times :)

**Comment by eddieajau** [comment]
Application package changes pulled in.  Only oddities are in the module/helper.php file lines 351 to 356 in the CMS - they may need a double check.

**Comment by eddieajau** [comment]
Client package merged.

**Comment by AmyStephen** [comment]
Louis - would it safe to assume that the two repositories were square on May 10th when Mark Dexter applied changes from the platform project to the SVN? (SVN Revisions 21325-6) I'm going to try to apply the SVN patches since that date (beginning from Revision 21347, on) and see how that goes.

**Comment by elinw** [comment]
Andrew there was a one line change to module helper done in the platform and nt the cms that definitely should be in the cms. There was a commit in the cms that changed that method slightly as part of the loadmodule improvement that I'll check over since it was part of my patch I think.

**Comment by eddieajau** [comment]
Thanks Elin - just need to know what change shouldn't be lost.

There's a patch in the CMS tracker by Rouven to improve syncing.  If I can get a few more good tests on that I'll get it merged.
http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=26346

**Comment by eddieajau** [comment]
Database package merged.

**Comment by eddieajau** [comment]
Error package merged.

**Comment by eddieajau** [comment]
Form, HTML, Language, Log, Mail, Plugin (*), and Registry packages merged and docblocks sync'd.

(*) The Plugin helper class has some code differences that still need looking into.

**Comment by elinw** [comment]
Andrew do you mean this line?

```
            if ($plugins[$i]->type == $type && ($plugins[$i]->name == $plugin ||  $plugin === null)) {
```

and these

```
                    if ( !isset( $plugin->params ) ) {
                        // Seems like this could just go bye bye completely
                        $plugin = self::getPlugin($plugin->type, $plugin->name);
                    }
```

I'll try to figure out what was going on there.

**Comment by elinw** [comment]
These changes were made in the platform on 11/6/7 
commit 18d44a7a4904b896447ac3a478ff2aecb26378ff

"Correct some errors in the router and unit test"

**Comment by elinw** [comment]
No that's wrong sorry, misunderstood the diff.

**Comment by elinw** [comment]
11c7f43e9ef2857bcd3b8313eacc7ebf0b7dfb95

June 24

There was no parallel commit made on the CMS.

**Comment by elinw** [comment]
Andrew this issue in the CMS tracker http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=24537  has already been committed here so you will probably come up with a mismatch there unless we do the commit to the cms first.

**Comment by elinw** [comment]
http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=26365   Has the changes for the plugin helper.

**Comment by elinw** [comment]
http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=26366  is a CMS patch for the module helper difference.

**Comment by elinw** [comment]
http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=24285  was committed to the platform but not the CMS, I've asked for testing in JBS.

**Comment by elinw** [comment]
http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=26241  This has been committed to platform but not CMS.

**Comment by eddieajau** [comment]
I believe we are now all merged except for Cache and Installer packages.  Amy, did you get anywhere with the Installer package?

**Comment by AmyStephen** [comment]
Yes, my Installer pull request was processed by Louis a week ago. It works just fine, thanks Andrew.

Planning on going with 11.2 for Molajo Alpha.
