### ISSUE TITLE
Bug into cache system - Cache folder deleted

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-platform#751]
In all my joomla 2.5.x test and  1.7.x installation I have the same problem
It is a bug in the file cache system
Instead of deleting the content of the cache folder the sytem delete the folder.

To reproduce the problem

1) activate Conservative caching
2) Select Cache lite
3) save the change

Try the site, clear the "Epired cache" all is fine
Go to the folder "administrator" and you see the folder "cache" is there

to get the problem

1) Put the caching to OFF
2) Save the change
3)go to the folder "administrator" and you see the folder "cache" is no more there

Try to clear the "Epired cache" and you will get an error "Error purging expired items"

Try to enable the file cache ... Ho no more file cache into the menu.

To correct the problem just recreate the folder "cache" into the administrator directory and all work now fine

**Comment by ghost** [comment]
fix proposed here
http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_id=8103&tracker_item_id=27788

fix:
 $cache = JFactory::getCache();
 $folders=JFolder::folders(JPATH_CACHE); New line
 foreach ($folders as $folder){                     New line
    $cache->clean($folder);                         Mod line
 }                                                             New line

Just after  $cache = JFactory::getCache(); at two place into the file lines 192 and 257 of the file for joomla 2.5.
path: administrator/components/com_config/models/
filename: application.php

the same fixe work on joomla 1.7.x (the file is not the same version, just find  the two line $cache = JFactory::getCache();)

**Comment by elinw** [comment]
This is a change in a CMS file so you should make a pull request in the CMS repository.

**Comment by realityking** [comment]
As Elin pointed out this seems to be a CMS issue.
