### ISSUE TITLE
Bug in JURI::buildQuery

### ISSUE THREAD

**Issue by ebitester1** [joomla/joomla-platform#833]
There is an error in JURI::buildQuery in last line:

```
return urldecode(http_build_query($params, '', '&'));
```

Using urldecode distort the data if the values ​​in $params array have special characters (& and =).

Example:

```
$a=array('a'=>array('b'=>array('e'=>123,'f'=>789),'c'=>456), 'd'=>'&h=123');
echo urldecode(http_build_query($a));
```

Output:

```
a[b][e]=123&a[b][f]=789&a[c]=456&d=&h=123
```

You can see a new element h.

I think that urldecode was used for beauty. It was assumed that urldecode will decode the square brackets. However, this function makes more changes!

You can completely remove urldecode. But if you want beauty, you can replace the last line with the following code:

```
return str_replace(array('%5B', '%5D'), array('[', ']'), http_build_query($params, '', '&'));
```

**Comment by realityking** [comment]
urldecode() wasn't added for beauty but for backward compatibility. The output of Joomla 1.5 (which couldn't use http_build_query()) had to match that of Joomla 1.6.

**Comment by realityking** [comment]
Didn't mean to close this, sorry.

**Comment by LouisLandry** [comment]
@ebitester1 would you be interested in creating a pull request for this?  Ideally we could get a couple of unit tests to make sure we don't have any regressions as well.

**Comment by dongilbert** [comment]
If you're still interested in this, please open a Pull Request on the CMS repo, as they are maintaining the platform now.

**Comment by LivioCavallo** [comment]
This has been closed but the problem remains.
In Joomla!3 (v.3.4.3) if you create a menu item of tagged-elements of a specific category, the generated link in the menu item will be invalid html, as it contains raw '[' and ']'.
(to reproduce the problem please look at the source html, or look at the page in IE or Chrome, as Firefox anyway shows embellished urlencoded links to the user!)

I think it should be fixed as proposed by ebitester1.

Or at leaset by removing the "superfluous" urldecode (is backward compatibility with Joomla1.5 still important?).

I did so in my code and so far (1) all works well.
