### ISSUE TITLE
JS issue in /html/html/grid.php

### ISSUE THREAD

**Issue by OctavianC** [joomla/joomla-platform#846]
All generated links that have href="#" and an onclick attribute should return false in the onclick attribute so that the user doesn't get forwarded to the href. This issue occurs in sort():
<code>href="#" onclick="Joomla.tableOrdering(...)"</code>
should be
<code>href="#" onclick="Joomla.tableOrdering(...); return false;"</code>

A cleaner way (in my opinion) would be for the tableOrdering() function to return false so you can use:
<code>href="#" onclick="return Joomla.tableOrdering(...)"</code>

This is correctly done in published()
<code>href="#" onclick="return listItemTask(...)"</code>

PS: I did search for "sort" but could not find anything, I'm hoping this is not a duplicate :)

**Comment by elinw** [comment]
Why don't you make a pull request for this? It's more likely to get a response that way.

**Comment by LouisLandry** [comment]
Ya, I'd love to review a pull request on it if you feel like making that change.

**Comment by eddieajau** [comment]
Closing this issue since there has been no follow up for 5 months.
