### ISSUE TITLE
Bug in JLog || JLoggerFormattedText

### ISSUE THREAD

**Issue by okonomiyaki3000** [joomla/joomla-platform#849]
JLoggerFormattedText::addEntry changes the value of $entry->priority to a string. This causes trouble if more than one logger is handling this entry (other loggers will find a string where they expected to find an integer). The solution is either to not make that kind of change to the entry at all or to clone $entry before passing to the logger class' "addEntry" method. I prefer cloning because it makes future errors of this type impossible.

**Comment by elinw** [comment]
Can someone clarify the status of this please.

**Comment by AmyStephen** [comment]
The change is in core. https://github.com/joomla/joomla-platform/blob/staging/libraries/joomla/log/log.php#L259
