### ISSUE TITLE
Tests failing with CMS merge

### ISSUE THREAD

**Issue by ianmacl** [joomla/joomla-platform#85]
As of commit https://github.com/ianmacl/joomla-platform/commit/9d7e34c6d0b10d6d2f4b6181b933706b29375cb6

> > > JPlatformTest::testIsCompatible.testIsCompatible with data set "wrong"  0.005464    1
> > > JPlatformTest::testIsCompatible.testIsCompatible with data set "empty"  0.005964    1
> > > JPlatformTest::testIsCompatible.testIsCompatible with data set "null"   0.005483    1
> > > JPlatformTest::testIsCompatible.testIsCompatible with data set "itself"     0.005449    1
> > > JPlatformTest::testIsCompatible.testIsCompatible with data set "version 1.5.22"     0.005445    1
> > > JPlatformTest::testIsCompatible.testIsCompatible with data set "version 1.7.0"  0.005435    1
> > > JPlatformTest::testIsCompatible.testIsCompatible with data set "version 11.1.0"     0.00545 7
> > > JPlatformTest.testGetLongVersion    0.565237    7
> > > JPlatformTest.testGetShortVersion   0.006641    7

The 1s and 7s at the end are test ages.  The first few just broke, the others have been broken for 7 commits.

**Comment by eddieajau** [comment]
Thanks should be fixed now.  Interesting what happens when you increment the version number :)

**Comment by ianmacl** [comment]
Test Name  
Duration  
Age   

> > > JPlatformTest::testIsCompatible.testIsCompatible with data set "wrong"  0.005464    1
> > > JPlatformTest::testIsCompatible.testIsCompatible with data set "empty"  0.005964    1
> > > JPlatformTest::testIsCompatible.testIsCompatible with data set "null"   0.005483    1
> > > JPlatformTest::testIsCompatible.testIsCompatible with data set "itself"     0.005449    1
> > > JPlatformTest::testIsCompatible.testIsCompatible with data set "version 1.5.22"     0.005445    1
> > > JPlatformTest::testIsCompatible.testIsCompatible with data set "version 1.7.0"  0.005435    1
> > > JPlatformTest::testIsCompatible.testIsCompatible with data set "version 11.1.0"     0.00545 7
> > > JPlatformTest.testGetLongVersion    0.565237    7
> > > JPlatformTest.testGetShortVersion   0.006641    7

Latest test results.

**Comment by eddieajau** [comment]
Sorry, forgot to push.  How are you getting those results?

**Comment by ianmacl** [comment]
Results come from jenkins.

Those seem to be fixed.  One failure now:
JParameterTest::testBind
JException: JLIB_REGISTRY_EXCEPTION_LOAD_FORMAT_CLASS

/opt/testing/hudson/data/jobs/platform/workspace/libraries/joomla/registry/format.php:52
/opt/testing/hudson/data/jobs/platform/workspace/libraries/joomla/registry/registry.php:264
/opt/testing/hudson/data/jobs/platform/workspace/libraries/joomla/html/parameter.php:146

Failure came from last commit.

**Comment by eddieajau** [comment]
Thanks.  Fixed now.
