### ISSUE TITLE
enhancement for JLog::addLogger

### ISSUE THREAD

**Issue by okonomiyaki3000** [joomla/joomla-platform#853]
It's great that you can add a logger for a specific combination of priorities and categories but wouldn't it be nice if you could add one that excluded specific categories? So, for example, you could add logging for anything except 'deprecation' messages.

A 4th parameter could be added to JLog::addLogger which could either be:
a) an array of categories to specifically exclude
b) a boolean switch that alters the behavior of the existing $categories parameter

I'm not sure which is preferable. 'a' is slightly more complex but offers more (probably unnecessary) flexibility. 'b' may be easier to understand, use, and implement. I would be happy with either. Actually, I will happily code either of them if there is support for this idea.

**Comment by elinw** [comment]
why don't you just make a pull request. It's really hard to get feed back from anyone when you don't have code and tests.

**Comment by LouisLandry** [comment]
@okonomiyaki3000 I think this is a great idea, and I would go with option B for simplicity.  If you put a pull request together I'll happily merge it.
