### ISSUE TITLE
Feed Caching does not work

### ISSUE THREAD

**Issue by Chraneco** [joomla/joomla-platform#858]
Test instructions:
- Set up a new instance of Joomla! with default sample data
- Create a new feed module in backend on position 'cpanel' with your favourite feed.
- Go to control panel and ensure that the feed module is displayed correctly
- Go to global configuration and enable caching
- Go to control panel and refresh the page
  -> An empty feed module will be displayed

I had a look at this and found out that the bug is in method 'getFeedParser' of class 'JFactory'. The cache controller 'callback' is used there for caching the feed using the 'init' method of SimplePie library as the callback function.

This produces two problems:
1. The return value of method 'init' is only a boolean which gets cached then. So the gain of that isn't very much.
2. 'getFeedParser' returns an instance of the SimplePie library. So if the library was initialised with 'init' afore, the 'get' method of the cache won't execute 'init' again. Thus, an uninitialised SimpliePie object is returned and so we get an empty feed module.

**Comment by elinw** [comment]
If you have a solution would you please go ahead and send a pull request? Thanks

**Comment by jptweb** [comment]
I am encountering this issue in Joomla 2.5.6

**Comment by elinw** [comment]
If you're experiencing this in the CMS would you please check in J3.0 since simple pie is not being used any more?

**Comment by Chraneco** [comment]
Hi,

in Joomla! 3.0 feeds don't seem to be cached at all with JFeed.

Which is the intended way for that?

Regards
Chraneco

**Comment by elinw** [comment]
I think you're really talking about a cms issue right now since the cms is using a version of JFeed, so you should probably put the report in the CMS tracker. What would be great is if you would look at the code in the JFeed pull request and see how it would be used to address this (or if there would be a problem interacting with cache.).

**Comment by Chraneco** [comment]
No, regarding JFeed I just answered to your question :-)

This issue is still about caching SimplePie which is implemented in the platform and used by the CMS (at least in Joomla! 2.5).
