### ISSUE TITLE
Platform 11.4 syntax bug

### ISSUE THREAD

**Issue by railgt** [joomla/joomla-platform#862]
Could someone take a look at loader.php _autoload() definition. It seems there is a syntax bug in preg_split.
 The actual line looks like that:
 $parts = preg_split('/(?>=[a-z])(?=[A-Z])/x', substr($class, 1));
 while it should be:
 $parts = preg_split('/(?<=[a-z])(?=[A-Z])/x', substr($class, 1));

?<= shall be used for look-behind assertion. Otherwise, the class name split may not work here.

**Comment by realityking** [comment]
Assigning to Louis since he wrote the autoloader.

**Comment by LouisLandry** [comment]
Can you give me a couple of examples that will fail with the current regex and pass with the updated one?

**Comment by railgt** [comment]
$class = 'className';
// what we have now
$parts = preg_split('/(?>=[a-z])(?=[A-Z])/x', $class));
print_r($parts); // will print Array ( [0] => className )

// what I suppose should be instead
$parts = preg_split('/(?<=[a-z])(?=[A-Z])/x', $class));
print_r($parts); // will print Array ( [0] => class [1] => Name )

I assume that the original idea was to provide the way to automatically generate a path to class storage based on the Camel naming. In the first example the path to the class will be /classname.php and in the second case it will be /class/name.php

**Comment by LouisLandry** [comment]
Well, that's an interesting example actually.  A class called `className` wouldn't pass our coding standards for class names, so it wasn't considered in this way.  All of our classes have a prefix capitol `J` then camel naming starting with a capital letter such as `JModel`, `JController`, `JApplicationWeb`, etc.

**Comment by railgt** [comment]
Agree. The given example was an example of the used RegEx expression. Funny thing - just downloaded the latest version and the code is correct. Here is the extraction:

private static function _autoload($class)
{
   // Only attempt to autoload if the class does not already exist.
   if (class_exists($class))
   {
      return;
   }

   // Only attempt autoloading if we are dealing with a Joomla Platform class.
   if ($class[0] == 'J')
   {
      // Split the class name (without the J) into parts separated by camelCase.
      $parts = preg_split('/(?<=[a-z])(?=[A-Z])/x', substr($class, 1));

```
  // If there is only one part we want to duplicate that part for generating the path.
  $parts = (count($parts) === 1) ? array($parts[0], $parts[0]) : $parts;

  // Generate the path based on the class name parts.
  $path = JPATH_PLATFORM . '/joomla/' . implode('/', array_map('strtolower', $parts)) . '.php';

  // Load the file if it exists.
  if (file_exists($path))
  {
     include $path;
  }
```

   }
}

Sorry for bugging you, but it looks Ok now.

**Comment by LouisLandry** [comment]
Don't be sorry.  Thanks for caring enough to bring it up and discuss it.  We need more people like you to do exactly that.  It also reminds me that I wanted to add 0-9 to the first character class in that regex.

Thanks again.
