### ISSUE TITLE
JLoggerCallback

### ISSUE THREAD

**Issue by okonomiyaki3000** [joomla/joomla-platform#866]
I'd like to suggest a new type of JLogger which can be instantiated with a callback function (passed in the $options array, of course) and which simply passes $entry to that function when addEntry is called.

**Comment by okonomiyaki3000** [comment]
Although this sounds simple enough, you'd want it to work with the lambdas (available since 5.3) in addition to the old 'create_function' and 'array' callback types. Currently this doesn't work because JLog::addLogger serializes $options to use it as a signature. PHP's lambdas can not be serialized. Trying to do so produces errors. So this can either be done with the caveat that only the old-school approach will work or some change could be made to JLog. I'm not sure how to fix it at the moment though. Would need a way to uniquely identify a lambda.

**Comment by okonomiyaki3000** [comment]
It seems that object comparison works as you'd hope with Closure objects. So, there is a way to support lambdas. A special case would need to be added to JLog::addLogger so that it checked a particular key on the $options array for the presence of a Closure object. If it finds one, it would need to swap it for some unique id for serialization then swap it back in afterward. 

I'm just talking to myself, maybe?

**Comment by elinw** [comment]
We're waiting for some code and tests to see how it would work.

**Comment by okonomiyaki3000** [comment]
It's included in this pull request: https://github.com/joomla/joomla-platform/pull/874

Let me know if you think it needs more tests or anything.

**Comment by elinw** [comment]
Okay in that case you can close this issue and just leave that one open.
#874

**Comment by okonomiyaki3000** [comment]
Over and out.
