### ISSUE TITLE
JV Headline module - How to configure a fixed banner?

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-platform#876]
Hi!

Could anyone help me set up JV Headline module? I'm trying to put a banner fixed on the module and keep rest working normally, and I have no idea how to do it. I created this image to explain better!

<img src='https://a248.e.akamai.net/assets.github.com/img/ee9db64258287fefba919ad46582f51cc1b5c038/687474703a2f2f692e696d6775722e636f6d2f6c744132622e706e67'>

(Sorry for my broken english).

I search in entire internet and found nothing, please help me.

**Comment by realityking** [comment]
This tracker is for issues related to the joomla platform. For end user support please use the Joomla forum at http://forum.joomla.org .

**Comment by ghost** [comment]
realityking, can you help me? I already post in the forum but nobody answer me. Please i really need help

**Comment by realityking** [comment]
Sorry, I don't know the module and this really isn't the place to ask.
