### ISSUE TITLE
Manifest SQL entires are not run for modules and plugins on discovery install

### ISSUE THREAD

**Issue by elinw** [joomla/joomla-platform#901]
http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=24956

This issue has been in the CMS tracker for a year and I'm just moving it here anyway. Ian or Sam could just decide to close if they wish, but it needs to get resolved one way or another..

**Comment by eddieajau** [comment]
I think this is fixed now. If not reopen or resubmit.
