### ISSUE TITLE
Some code to keep valid HTML when splitting or truncating

### ISSUE THREAD

**Issue by ebird2211** [joomla/joomla-platform#929]
At least the loadmodule and pagebreak plugins perform splitting and/or truncating of HTML, and inserting HTML fragments in existing HTML. This may break the validity - here's some code that makes sure HTML stays valid. Included are a rewrite for loadmodule and a small patch for pagebreak.

Hmm - it seems I cannot attach code or patches - please see http://joomlacode.org/gf/download/trackeritem/27932/72670/27932_loadmodule_27748_pagebreak-1.patch

**Comment by elinw** [comment]
Since this uses Git, you need to make a fork of the repository, edit it, and then make a pull request back. If it is just one file you can do it completely online (navigate to the file and click Fork and Edit). Since you are adding a new file, however, that really won't work.

This patch seems to include  a number of unrelated changes and CMS changes.  Only platform pieces should be submitted to this tracker.

**Comment by ebird2211** [comment]
Hi Elin,

thanks for the pointer - I'm still quite new to this stuff as you can easily see :) so please bear with me. I already made the fork however my Eclipse still has issues with the upstream push - I need to sort that out, I don't want to use the command line tools if not at all necessary. Yeah, most of the time I'm lazy ;-)

Best wishes,
Ernest

-----Ursprüngliche Nachricht-----
Von: elinw [mailto:reply@reply.github.com] 
Gesendet: Sonntag, 26. Februar 2012 17:37
An: ebird2211
Betreff: Re: [joomla-platform] Some code to keep valid HTML when splitting or truncating (#929)

Since this uses Git, you need to make a fork of the repository, edit it, and then make a pull request back. If it is just one file you can do it completely online (navigate to the file and click Fork and Edit). Since you are adding a new file, however, that really won't work.

This patch seems to include  a number of unrelated changes and CMS changes.  Only platform pieces should be submitted to this tracker.

---

**Comment by stefanneculai** [comment]
I think you should do Pull Request on your commit mentioning the no of the issue. That worked for me.

Stefan

**Comment by elinw** [comment]
Any update on this? See #1413

**Comment by elinw** [comment]
The link is sending me to an invalid page.  Is there a reason this is a platform issue/solution if it is about fixin cms plugins?

**Comment by dongilbert** [comment]
The link is no longer valid. Closing
