### ISSUE TITLE
JMail addAttachment ignores parameters (filename, encoding, type) 

### ISSUE THREAD

**Issue by brandtOSS** [joomla/joomla-platform#930]
The addAttachment method of the JMail class does not pass on the parameters
$name, $encoding and $type to its PHPMailer parent class.
This makes it impossible to e.g. specify another file name for an attachment.

The patch: https://github.com/brandtOSS/joomla-platform/commit/4c173d20e06578ab9da32468e00da85bd1c530e2

**Comment by realityking** [comment]
Closing, this is dealt with in #931.
