### ISSUE TITLE
JDatabaseDriver extends JDatabase

### ISSUE THREAD

**Issue by AmyStephen** [joomla/joomla-platform#976]
Wondering if it might be better if the new class, JDatabaseDriver did not extend JDatabase. 

If JDatabase just redirects the call to the new method, it should accomplish the same thing while allowing the eventual removal of the deprecated class without any change to the new class.

Thanks for considering.

**Comment by AmyStephen** [comment]
Or, now that I think about it, why not just have JDatabase extend JDatabaseDriver and call the parent method?

That would still allow the transition and complete removal without impacting the new class.

**Comment by AmyStephen** [comment]
Along the same lines, it might be better not to start the new class with the deprecated method getUTFSupport.  

If it stays, then the comment is wrong:

https://github.com/joomla/joomla-platform/blob/staging/libraries/joomla/database/driver.php#L732

**Comment by realityking** [comment]
I'm not sure what you're saying. JDatabaseDriver extends JDatabase so any type hints and checks for instanceof JDatabase keep working, it won't stay around forever.

**Comment by AmyStephen** [comment]
Wait - are you saying JDatabaseDriver and JDatabase both go away? 

If so, I am very confused as to what the direction is here.

**Comment by AmyStephen** [comment]
This is what I am suggesting be done instead, Rouven:

class JDatabaseDriver 
{
  function no_deprecated_methods_only_new_ones () {}
}

class JDatabase extends JDatabaseDriver
{
    function leave_deprecated_methods_in_the_old_class () {}
}

With this approach, existing type hints and instanceof checks for JDatabase still work, right? 

When it's time for JDatabase and it's deprecated methods to go away, simply remove it from the package. 

The new class: JDatabaseDriver (and the developer API) then reflect _where we are going_ and no changes will be required to the new class when the old class and deprecated methods are finally removed. 

Just trying to point out as a developer using the Joomla framework code, I find this approach confusing. Flipping things around helps to send a clear signal as to where the codebase is heading and therefore where I, as a developer, should focus my work.

(Again, that is if the JDatabaseDriver is where it's all going, if that's not the case, then I am just lost. :-P )

**Comment by realityking** [comment]
Sorry if I was unclear, JDatabseDriver is not going to go away, JDatabase is.

Deprecated properties/methods should probably move over to JDatabase, it would be consistent with earlier work.

As for the rest I don't quite understand what you're saying.

**Comment by AmyStephen** [comment]
Rouven - no reason to apologize, appreciate your responses.

Sounds like you and I agree on the methods/properties. That's a big part of what I found confusing.

The only other confusion was that, IMO, it makes more sense for JDatabase to extend JDatabaseDriver (rather than as it is now where "permanent" class JDatabaseDriver extends the deprecated class, JDatabase.)

Good enough. Thanks again for your feedback. :)

**Comment by realityking** [comment]
I think the reason why JDatabaseDriver extends JDatabase and not the other way around is that we can have JFactory::getDbo() and possibly similar code adapted to how it should look like. In theory we'll have to do no changed at all when we drop JDatabase outside the database package.

Can this issue be closed?

**Comment by LouisLandry** [comment]
Actually, the real reason it was done the way it was done ... and generaly speaking either are valid is because of the extended classes.

I didn't think it was a good idea to do something like

``` php
<?php
class JDatabase extends JDatabaseDriver {}

class JDatabaseDriverMysql extends JDatabase {}
class JDatabaseDriverSqlite extends JDatabase {}
```

Meanwhile, we'd have to do the following for backward compatibility classes:

``` php
<?php
class JDatabaseMySQL extends JDatabaseDriverMysql {}
class JDatabaseSQLite extends JDatabaseDriverSqlite {}
```

Aside from the somewhat awkward hierarchy established there, it means that I now have to edit N files for N drivers when it's time to drop JDatabase.  Doing it the way we've done it means that we edit one file and drop one file: `JDatabaseDriver` and `JDatabase` respectively.  Ultimately the way it's done now seemed cleaner.

**Comment by AmyStephen** [comment]
Thanks for the explanation. :)

**Comment by AmyStephen** [comment]
@LouisLandry - 

I am sorry, but I didn't see your comments before I responded. I see what you are saying. 

Might have been enough to just have JDatabaseDriver extend JDatabase without also including the deprecated methods (or have just done one or the other) -- but I get it now. 

I appreciate your response. It helps me learn. Thanks for taking the time to help me understand.
