### ISSUE TITLE
issue with JFormFieldInteger 

### ISSUE THREAD

**Issue by tbela99** [joomla/joomla-platform#983]
JFormFieldInteger  does not allow me to do this

<input type="integer" first="100" last="0" step="-1" />

I want 100 to be the first number and 0 to be the last but in the code:

for ($i = $first; $i <= $last; $i += $step)

will never run

**Comment by tbela99** [comment]
here is the xml declaration for the element
<input type="integer" first="100" last="0" step="-1"

**Comment by eddieajau** [comment]
Fixed.

**Comment by tbela99** [comment]
great!
